CHANGELOG.md, CONTRIBUTING.md
* Adds missing sections
* Reorganizes and reduces existing sections
=> Restructure CONTRIBUTING.md

.github/workflows/docs.yml, CHANGELOG.md, docs/scripts/convert_code_to_documentation.py, tox.ini
This PR introduces the action that allows us to build the documentation using Github pages.
=> Add documentation github action

CHANGELOG.md, pyproject.toml
Adds some basic metadata to our pyproject.toml file
=> Project metadata for pyproject.toml

CHANGELOG.md, README.md
=> Ditch Conda

CHANGELOG.md, baybe/constraints/discrete.py, docs/userguide/constraints.md, examples/Constraints_Discrete/custom_constraints.py, examples/Constraints_Discrete/mixture_constraints.py, tests/conftest.py, tests/test_constraints_discrete.py
Adds text for the missing constraints and fixes some minor things
=> Finish Constraints User Guide

CHANGELOG.md, baybe/campaign.py, baybe/constraints/conditions.py, baybe/constraints/discrete.py, baybe/telemetry.py, baybe/utils/basic.py, baybe/utils/numeric.py, baybe/utils/sampling_algorithms.py, docs/conf.py, mypy.ini, pyproject.toml
Activate mypy for various code parts
- `constraints`
- `telemetry`
- `campaign`
- most utils, except the ones that are under strong change in #79 and #86
=> Misc MyPy Activations

CHANGELOG.md, baybe/utils/__init__.py, examples/Backtesting/botorch_analytical.py, examples/Constraints_Continuous/hybrid_space.py, examples/Constraints_Continuous/linear_constraints.py, examples/Searchspaces/continuous_space_botorch_function.py, examples/Searchspaces/discrete_space.py, examples/Searchspaces/hybrid_space.py
I made the changes as described in [this discussion](https://github.com/emdgroup/baybe/discussions/100).
=> Remove botorch wrapper from namespace

tests/hypothesis_strategies/dataframes.py, tests/serialization/test_dataframe_serialization.py
Fixes the dataframe strategy as proposed in https://github.com/HypothesisWorks/hypothesis/issues/3859
=> Fix dataframe hypothesis strategy

README.md, docs/conf.py
Update the year and author information
=> Update project metadata

CHANGELOG.md, baybe/recommenders/base.py
Performs a small refactoring in recommenders to enable hybrid space metadata marking which was previously ignored
=> Fix hybrid metadata

CHANGELOG.md, baybe/searchspace/discrete.py, tests/hypothesis_strategies/alternative_creation/test_searchspace.py
This PR adds the option to control the number of active (i.e. non-zero) parameters in the simplex construction of discrete search spaces.
=> Nonzero simplex parameter control

.github/workflows/ci.yml, .github/workflows/regular.yml, CHANGELOG.md
enables reminders via https://github.com/marketplace/actions/issue-reminder
=> Enable repo reminders

CHANGELOG.md, baybe/campaign.py
=> Release 0.7.4

.github/workflows/regular.yml
changing the docs step python version to 3.9 as it suffers from the same issue fixed a while ago in the documentation action
=> Fix Regular Action

CHANGELOG.md, baybe/searchspace/discrete.py, docs/userguide/searchspace.md
This PR contains the first version of the new `SearchSpace` user guide. It is designed with what @Scienfitz and I discussed previously in mind. Feedback is very much welcome :)
=> New search space userguide

CHANGELOG.md, docs/userguide/simulation.md, examples/Transfer_Learning/backtesting.py, examples/Transfer_Learning/backtesting_dark.svg, examples/Transfer_Learning/backtesting_light.svg
This PR introduces a user guide for BayBE's simulation capabilities. It briefly introduces the core concepts like `lookup` and the different kinds of simulation available.
Note that this PR was not designed to be perfect and final. Since there might or might not be an upcoming refactoring of the simulation capabilities, the goal of this PR was to have *some reasonable* user guide, not a perfect one.
In addition, I realized that there was no example using the `simulate_transfer_learning` function so far. I consequently added one example and called it "Cross Task Learning" as this was the best description I could find. The example is heavily based on the other Transfer Learning example.
=> Simulation userguide

CHANGELOG.md, pyproject.toml, tox.ini
Upgrades ONNX version to fix recent vulnerability. Fixes #143.
=> Fix ONNX vulnerability

CHANGELOG.md, baybe/recommenders/pure/bayesian/base.py, baybe/surrogates/gaussian_process.py
* Increases threshold for low-dimensional GP priors
* Replaces the MLL optimizer
* Casts best_f to float to suppress botorch warning
=> Botorch settings

README.md
Gives our README a shiny touch by adding emojis
=> Emojification

CHANGELOG.md, baybe/campaign.py, baybe/constraints/base.py, baybe/constraints/validation.py, baybe/parameters/utils.py, baybe/searchspace/continuous.py, baybe/searchspace/core.py, baybe/searchspace/discrete.py, baybe/searchspace/validation.py, baybe/telemetry.py, baybe/utils/basic.py, baybe/utils/dataframe.py, baybe/utils/interval.py, mypy.ini, tests/hypothesis_strategies/alternative_creation/test_searchspace.py, tests/test_searchspace.py
Activates `mypy` for search spaces.
=> Mypy for search spaces

docs/userguide/simulation.md
Fixed code snippet to correct function in simulate_experiment section
=> Correct simulate_scenarios to simulate_experiment in docs

CHANGELOG.md, baybe/simulation.py
Fixes #200 by deduplicating lookup parameter configurations before dropping search space entries in `ignore` mode
=> Fix lookup bug in simulation

CHANGELOG.md, tests/hypothesis_strategies/constraints.py, tests/hypothesis_strategies/parameters.py, tests/serialization/test_constraint_serialization.py
Implements `hypothesis` strategies for constraints and adds the corresponding serialization roundtrip tests.
=> Hypothesis for constraints

CHANGELOG.md, baybe/kernels/priors/__init__.py, baybe/kernels/priors/basic.py, baybe/utils/validation.py, tests/conftest.py, tests/hypothesis_strategies/basic.py, tests/hypothesis_strategies/priors.py, tests/hypothesis_strategies/utils.py, tests/test_iterations.py
- enable more priors
- add basic prior iteration tests
=> More Priors

CHANGELOG.md, baybe/telemetry.py, pyproject.toml
This ditches `requests` as suggested in #233
=> Ditch `requests`

CONTRIBUTORS.md, README.md
This PR fixes a few minor issues in README.md
=> Minor README fixes

CHANGELOG.md, docs/conf.py, docs/references.bib, docs/userguide/transfer_learning.md, pyproject.toml
Updated with info and examples for when and when not to use it, feel free to suggest more examples
=> Update TL User Guide

CHANGELOG.md, baybe/constraints/discrete.py, tests/conftest.py, tests/test_constraints_polars.py
Feature: Polars support for `DiscreteNoLabelDuplicatesConstraint` and `DiscreteLinkedParametersConstraint`
Tests: Added in `test_constraints_polars.py`
=> Polars: Translate linked parameter and no label duplicate to polars

CHANGELOG.md, CONTRIBUTORS.md, baybe/searchspace/discrete.py, pyproject.toml, tests/test_constraints_polars.py
Feature: Speed up `from_product()` through using Polars cross-join and filtering.
Test: Added to `test_constraint_polars.py`
=> Polars: from_product() implementation

baybe/surrogates/gaussian_process/presets/default.py
Some previous PR introduced broken docstring links. This PR fixes the links.
=> Fix broken docstring links

baybe/surrogates/base.py, baybe/surrogates/custom.py, baybe/surrogates/gaussian_process/core.py, baybe/surrogates/gaussian_process/presets/core.py, baybe/surrogates/gaussian_process/presets/default.py, baybe/surrogates/linear.py, baybe/surrogates/ngboost.py, baybe/surrogates/random_forest.py, baybe/surrogates/utils.py, docs/conf.py, mypy.ini
This PR finally enables mypy for the surrogates package
=> Mypy for surrogates

docs/known_issues.md
This PR adds a small section regarding the installation of `polars` to the known issues page, implementing #403 .
=> Add Polars installation issues to known_issues

.pre-commit-config.yaml
Let us deprive the devil of his power
=> Disable pre-commit.ci autofixing

examples/Multi_Target/pareto.py
Avoid exporting the SMOKE_TEST plot
=> Fix Pareto example plot export

CHANGELOG.md, docs/userguide/constraints.md
This PR adds explanations for the `ContinuousCardinalityConstraint` and the `DiscreteCardinalityConstraint` to the user guide.
=> User guide for cardinality constraints

baybe/constraints/conditions.py, baybe/kernels/composite.py, baybe/parameters/base.py
Avoids `mypy` complaints for yet unsupported converters using our custom helper
https://github.com/python/mypy/issues/17547
=> Fix converter typing

CHANGELOG.md, baybe/acquisition/__init__.py, baybe/acquisition/_builder.py, baybe/acquisition/acqfs.py, docs/conf.py, tests/hypothesis_strategies/acquisition.py
This PR adds the regular (non-log) `qNoisyExpectedHypervolumeImprovement` acquisition function.
=> More hypervolume acquisition functions

tests/constraints/test_constraints_polars.py
Temporarily xfail some polars tests due to regression:
https://github.com/pola-rs/polars/issues/23187#issuecomment-2983037337
=> xfail polars tests

.github/workflows/ci.yml, .pre-commit-config.yaml, tox.ini
A little quality-of-life improvement that completely automates lockfile handling
=> Lockfile check via pre-commit

README.md
Brings back the downloads badge since the PyPI stats service is now up again.
=> Bring back downloads badge
