emdgroup/baybe

- CHANGELOG.md
- docs/scripts/convert_code_to_documentation.py
- tox.ini
This PR prevents the documentation building from failing when encountering an error.
This is achieved by replacing the `check_call` commands by `run` in case of an error that is raised.
> Fix open issues in doc generation

- CHANGELOG.md
- docs/_static/custom.css
- docs/conf.py
- docs/index.md
- docs/scripts/convert_code_to_documentation.py
- docs/userguide/campaigns.md
- docs/userguide/constraints.md
- docs/userguide/parameters.md
- docs/userguide/recommender.md
- docs/userguide/searchspace.md
- docs/userguide/simulation.md
- docs/userguide/strategy.md
- docs/userguide/surrogates.md
- docs/userguide/targets.md
- docs/userguide/userguide.md
- pyproject.toml
- tox.ini
This PR introduces the furo theme for creating the docs. It also introduces a few minor fixes like repairing a non-functional link in CONTRIBUTING.md and by ignoring links that are not yet active. Furthermore, the README.md file is now the "Welcome" page, i.e., the first page that is seen when clicking on the documentation.
Note that the coloring scheme is not yet final, and probably the most important aspect to discuss. Further note that this theme has a light and a dark mode.
> Use furo theme for docs

- .github/workflows/ci.yml
- .github/workflows/docs.yml
in particular this makes the readme check optional
Not included and not intended:
- better caching seems non trivial, caches are only shared between main and current branch, but not between all development branches
- fix for PyPI test
> Actions Changes

- README.md
- pyproject.toml
As discussed, this PR removes the authors from the pyproject.toml and includes a corresponding section in the README.
> Move authors from pyproject to README

- CHANGELOG.md
- baybe/utils/dataframe.py
- examples/Backtesting/full_lookup.py
added some literature references where its appropriate but was missing
Ideally we can have last push form everyone to add references in case there are more places where stuff from other work was used or strongly inspired
> Add Literature References

- docs/_static/custom.css
- docs/conf.py
This PR adjusts two colors:
1. Text within table header is now white across light and dark mode
2. The background of in-line code like `x_y` now has a slightly darker background in dark mode
> Minor color adjustments

- README.md
- baybe/constraints/conditions.py
- docs/conf.py
- docs/userguide/constraints.md
- docs/userguide/parameters.md
- docs/userguide/transfer_learning.md
- docs/userguide/userguide.md
Includes Doc pages for
- constraints
- parameters
Other changes:
- Enable dollarmath in doc config
- Created dummy page for transfer learning
> Userguide: Constraints and Parameters

- .github/workflows/release.yml
- CHANGELOG.md
Changes the release pipeline to also publish source distributions (sdists)
NOT activated: `skip_existing` so this new pipeline would prob fail if triggered on the existing tags
> Release Sdists

- CHANGELOG.md
- baybe/objective.py
- baybe/parameters/numerical.py
- baybe/targets/numerical.py
- baybe/utils/interval.py
- mypy.ini
- tests/test_deprecations.py
Enables `mypy` for the `Interval` class, which are used by targets (done in #54) and parameters (done in #28). Along the way, adds missing type hints and cleans up the class properties.
In particular, replaces the somewhat misleading `is_finite` and `is_bounded` methods with the common and easy-to-understand mathematical definitions `is_open`, `is_half_open` and `is_closed`, ensuring backward compatibility via deprecation mechanisms.
@AVHopp , @Scienfitz: Note that the PR builds upon #54, in order to configure the right diff view.
> Mypy for intervals

- CHANGELOG.md
- docs/conf.py
- docs/scripts/convert_code_to_documentation.py
- docs/templates/custom-attribute-template.rst
- docs/templates/custom-module-template.rst
This PR fixes the following minor errors in the documentation.
1. The `Smiles` type alias introduced in `parameters.substance`. This type alias is manually configured in `conf.py`. In order to avoid the documentation to load all of the attributes and functions of `str`, the templates were changed slightly to not include those, resulting in the output shown at the end.
2. The generics in `baybe.utils.basic`. Sphinx behaves weird when using generics (see https://github.com/sphinx-doc/sphinx/issues/10974). Thus, an exception was included in the nitpick_ignore dictionary, eliminating the error.
> Fix type alias and generic in documentation

- CHANGELOG.md
- README.md
- docs/userguide/constraints.md
- docs/userguide/parameters.md
- pyproject.toml
- tests/docs/test_docs.py
- tests/docs/utils.py
Adds a test that pipes all user guide code blocks through ruff to check for proper formatting. Run `pytest -s tests/docs/test_docs.py` to see the necessary formatting changes that can be copy-pasted.
> Formatting test for user guide code blocks

- .pre-commit-config.yaml
- CHANGELOG.md
- baybe/parameters/validation.py
- pydoclint.toml
- pyproject.toml
This PR changes the way that pydoclint is used. Previously, it was used as a stand-alone linter. This PR changes this and introduces it as a plugin for flake8.
The reason for this change is that (due to a previous error), pydoclint did not use the provided configuration file. Once this was changed, I realized that pydoclint does **not** allow you to use `noqa` for making in-line exceptions of specific error codes. This is only available when using it as a flake8 plugin (see https://jsh9.github.io/pydoclint/how_to_ignore.html).
For that reason, flake8 was reintroduced. It is configured in a way that it *only* reports the errors related to pydoclint and uses the pre-defined configuration file (see https://jsh9.github.io/pydoclint/ Section 2.2.)
Also, this PR adds one `noqa` that was …
> Use pydoclint as flake8 plugin

- CHANGELOG.md
- docs/_static/custom.css
Use a more appropriate margin computation (using relative values only) such that the appearance is good both on desktop and mobile version.
> Adjust margins in documentation

- .github/workflows/ci.yml
- CHANGELOG.md
- docs/scripts/convert_code_to_documentation.py
This PR changes the way the examples are being ignored if requested.
Now, when using the corresponding flag, the examples are still built but the notebooks are no longer constructed. As a consequence, building the documentation without the examples can now be used to check link integrity across all of BayBE. 
On my local machine, the speed-up was by a factor of 3.
> Build but do not execute examples when ignoring them

- CHANGELOG.md
- docs/userguide/campaigns.md
- examples/Basics/campaign.py
- tests/conftest.py
- tests/docs/test_docs.py
This PR reorganizes the campaign user guide and thus implements #60 .
The user guide is now way more informative, contains more details and better explanation. As there a lot of the code and specifically the explanations in the new user guide and the previous basic examples were duplicate, the corresponding example was trimmed down and condensed.
> Campaign user guide

- .github/workflows/docs.yml
This change intends to trigger the publication of docs to only-on-release
Currently its published on each update to main
it means the docs (starting from the next release) will only be online for the latest published release (also known as `stable`)
the publication on merge-into-main (also known as `latest`) can be reenabled once we figured out multi-version docs
> Change docs publishing trigger

- CHANGELOG.md
- CONTRIBUTORS.md
- README.md
I think it's better to get to the quick start sooner, and leave the more in-depth installation options towards the end.
I also think it might be worth using code formatting for the `df` output. For some reason, when I initially went through the docs I was under the impression there weren't any outputs (this was the case when I ran the code in Colab).
> Reorder README sections and print dataframe

- docs/scripts/convert_code_to_documentation.py
- docs/scripts/utils.py
This PR creates a new file under docs/scripts that contains utilities for building the documentation.
The reasons for this change are mainly
1. We might need some more utilities for properly including figures in light/dark mode in the examples
2. The conversion file contained functions that are used in the conversion, but technically not part of the conversion itself (like `adjust_banners`).
The only content-wise change is that the `convert_examples` function (which now lives in `utils`) has another argument in its signature for ignoring the examples. Previously, this was not necessary as the global flag was used. Other than that, no changes were made.
> Move doc building utilities to separate file

- CHANGELOG.md
- baybe/campaign.py
- baybe/exceptions.py
- docs/userguide/campaigns.md
- examples/Constraints_Continuous/hybrid_space.py
- examples/Constraints_Continuous/linear_constraints.py
- examples/Multi_Target/desirability.py
- tests/test_constraints_continuous.py
- tests/test_deprecations.py
This PR optimizes the public attributes of the campaign class and which of those are exposed via the constructor. 
The corresponding admonitions in the user guide (that warned about these attribute) are removed. 
Further, the PR deprecates the `numerical_measurements_must_be_within_tolerance` flag as a class attribute and turns it into a method parameter of `add_measurements`.
> Refactor exposed campaign attributes

- docs/scripts/utils.py
- examples/Backtesting/botorch_analytical.py
- examples/Backtesting/custom_analytical.py
- examples/Backtesting/full_initial_data.py
- examples/Backtesting/full_lookup.py
- examples/Backtesting/hybrid.py
- examples/Backtesting/impute_mode.py
- examples/Backtesting/multi_target.py
- examples/Basics/strategies.py
- examples/Constraints_Continuous/hybrid_space.py
- examples/Constraints_Continuous/linear_constraints.py
- examples/Constraints_Discrete/custom_constraints.py
- examples/Constraints_Discrete/dependency_constraints.py
- examples/Constraints_Discrete/exclusion_constraints.py
- examples/Constraints_Discrete/mixture_constraints.py
- examples/Custom_Surrogates/custom_architecture_sklearn.py
- examples/Custom_Surrogates/custom_architecture_torch.py
- examples/Custom_Surrogates/custom_pretrained.py
- examples/Custom_Surrogates/surrogate_params.py
- examples/Searchspaces/continuous_space_botorch_function.py
- examples/Searchspaces/continuous_space_custom_function.py
- examples/Searchspaces/discrete_space.py
- examples/Searchspaces/hybrid_space.py
- examples/Serialization/basic_serialization.py
- examples/Serialization/create_from_config.py
- examples/Serialization/validate_config.py
This PR fixes a bug that erased the output of the examples in the documentation.
The package `jupytext` which was introduced earlier for the conversion of the examples to jupyter notebooks does not include the output of executed notebooks to a converted markdown **by design**. This PR thus re-introduces `jupyter` for this step of the conversion.
Also, this PR introduces some visual fixes to all of the examples, since the comments were not rendered properly.
**IMPORTANT:** The only changes in the examples are additions and deletions of new empty lines. No other changes were done in the examples, it is thus fully sufficient to locally build the docs and review the examples there.
> Fix example output in documentation

- CHANGELOG.md
- baybe/searchspace/discrete.py
This PR implements a hotfix to prevent `TaskParameter`s from disappearing from the computational representation in cases where the search space contains only one task parameter value. The bug was caused due the removal of singular-valued columns which is automatically done in the exp-to-comp conversion of the search space. The logic of the latter needs to be refined in general, but this is out of scope of this PR.
> Hotfix: Disappearing Task Parameters

- CHANGELOG.md
- examples/Serialization/basic_serialization.py
Remove the `SubstanceParameter` from the basic serialization example so that it can run without requiring `chem` dependencies
> Remove `SubstanceParameter` from basic serialization example

- CHANGELOG.md
- baybe/searchspace/discrete.py
- tests/hypothesis_strategies/alternative_creation/test_searchspace.py
- tests/hypothesis_strategies/parameters.py
- tests/serialization/test_searchspace_serialization.py
This PR adds a new `SubspaceDiscrete.from_simplex` convenience constructor that is useful for mixture use cases. In particular, it enables such cases when an API is involved, as the two existing alternatives will not work here:
* `from_product` in combination with sum constraints suffers from the exponential blowup of parameter configurations
* `from_dataframe` requires sending excessively large requests to the API (since the requests need to contain the full enumerated search space)
> `SubspaceDiscrete.from_simplex` convenience constructor

- .github/workflows/docs.yml
The docs pipeline currently fails due to some issue with `__pycache__` and py311. This PR thus changes the docs pipeline version to 310 and allow manual triggering to ship the docs for the latest 0.7.3 release.
> Fix docs pipeline

- .github/workflows/docs.yml
- README.md
The `__pycache__` error also occurs on py310 and needs to be further investigated. Thus, temporarily changing to py39.
> Change docs pipeline python version to 3.9

- CHANGELOG.md
- baybe/recommenders/base.py
- baybe/recommenders/bayesian/base.py
- baybe/recommenders/bayesian/sequential_greedy.py
- baybe/recommenders/nonpredictive/base.py
- baybe/recommenders/nonpredictive/sampling.py
This PR refactors the recommender methods and finally removes much of the boilerplate code that was caused by suboptimal class layouts/hierarchies. In particular:
* Common logic is now consistently pulled up to the base classes (e.g. the default `_recommend_*` methods and their fallback logic)
* The `_select_candidates_and_recommend` helper function has been decoupled from `SearchSpace` and is now integrated into the base class logic, avoiding unnecessary passing around of callables and flags
* With the new lean hierarchy, the signatures of all recommend-related methods have been unified across subclasses. In particular `_recommend_hybrid` now always expects the pre-selected discrete candidates, which are passed down from the highest hierarchy level. This provides a common interface, …
> Refactor recommender methods

- CHANGELOG.md
- baybe/utils/chemistry.py
Make the cache directory configurable
This unblocks sue cases that could not sue baybe because a cache directory could not be created due to permission issues
- new environment variable `BAYBE_CACHE_DIR`
- CHANGED: if its not present, the folder `tempdir/.baybe_cache` will be used, `tempdir` is found via the builtin `tempfile` package which scans for folders enabled where the current user can write files, maybe theres a higher chance that this works compared to the userhome (eg in cases where theres no normal user like on foundry or docker etc)
- if its equal to "", disk caching is not done at all
- if its anything else it caches into the specified folder
Note that it would prob make sense to move some if this to a `utils/caching.py` but given its not used anywhere else I've not done that …
> Configurable Cache Dirs

- CHANGELOG.md
- baybe/telemetry.py
Telemetry currently sues `getpass.getuser()` as suggested here https://stackoverflow.com/questions/3724634/cross-platform-solution-for-getting-current-login-name-in-python
to get the username of the current user
However, on Windows it can happen that this throws an exception. If non of the checked environment variables contains a username, the function goes via `import cwd` which will result in `ModuleNotFound` error on Windows. 
This hotfix simply catches that case and sets a default username for that case.
This should unblock baybe failing for some Windows users
This PR does NOT optimize order of operations in telemetry which will be revisited when enabling global Telemetry
> Hotfix: Fallback for Windows-related getuser() issue

- CHANGELOG.md
- baybe/telemetry.py
- telemetry was accidentally disabled since mypy was activated for this module
- reason was: import caused an exception at runtime
- that exception was however broad accepted and telemetry disabled
- although this board except has caused a hidden issue here, its still the way to go as we dont want any user affected by any telemetry issue
in this process the old `logger` way of warning was replaced by the `warnings.warn`, as was recently done in various other submodules
> Hotfix: Telemetry Was Accidentally Disabled

- CHANGELOG.md
- docs/scripts/utils.py
This PR ensures that long lines are wrapped in the files that are created when executing the examples as jupyter notebooks.
A line is now wrapped when it is longer than the size that we allow for our python code, which is 88 characters. The only exception is when a link in detected since a line wrap might break this link.  This is done by checking whether the sequence `](` is present in the line.
> Add line wrap for examples in documentation

- CHANGELOG.md
- CONTRIBUTORS.md
- baybe/constraints/base.py
- baybe/parameters/base.py
- baybe/parameters/numerical.py
- baybe/searchspace/continuous.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- baybe/utils/dataframe.py
- pyproject.toml
This PR introduces a new printing function that can be used to have a prettier print (compared to the standard one). However, we still need to discuss what exactly a user would like to see in a simplified / pretty print and remove the hard-coded numbers.
But here are some notes:
- The current pretty_printing_dataFrame() prints only the first 10 rows and 5 columns of the handed over dataFrame object.
- The print function only prints the relevant search space, so if the continuous one is not used, then it will not be printed.
- We can get rid of the cartesian functions, but like mentioned before, we need to set our exact goal of the pretty printing function.
> Include pretty printing for search spaces

- CHANGELOG.md
- docs/scripts/utils.py
This PR removes the ugly progress bars in the executed examples.
The progress bars are automatically created by `xzypy` when executing our various simulation methods. Since I did not want to change these functionalities and since I did not find any "global" way of deactivating the progress bars, they are now removed in the post-processing of the example scripts. The corresponding lines are identified via the substring `s/it` and `it/s` and are removed.
> Remove progress bar in examples

- .pre-commit-config.yaml
- CHANGELOG.md
- examples/Transfer_Learning/Transfer_Learning_Header.md
- examples/Transfer_Learning/basic_tl.py
- examples/Transfer_Learning/basic_transfer_learning.py
- examples/Transfer_Learning/basic_transfer_learning_dark.svg
- examples/Transfer_Learning/basic_transfer_learning_light.svg
This PR introduces a basic Transfer Learning example, including the SMOKE_TEST functionality and the multi-version plotting.
This branch is currently based on the corresponding branch that implements SMOKE_TEST and multi-version plotting. ONly the last 3 commits are actually relevant.
Note that this PR also makes typos ignore .svg files, since these should definitely not be checked for typos.
> Basic Transfer Learning example

- CHANGELOG.md
- baybe/recommenders/deprecation.py
- baybe/recommenders/meta/sequential.py
- baybe/recommenders/naive.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/recommenders/pure/bayesian/sequential_greedy.py
- baybe/recommenders/pure/nonpredictive/clustering.py
- mypy.ini
this is based on PR #146 
This fixes types in the recommender package
except:
- assignment errors which cannot currently be solved as we explicitly expect an error if a recommender that cannot handle 0 data is used, this will be fixed once thats enabled for the bayesian one
> Mypy for recommenders

- examples/Backtesting/custom_analytical.py
- examples/Backtesting/full_initial_data.py
- examples/Backtesting/full_lookup.py
- examples/Backtesting/hybrid.py
- examples/Backtesting/impute_mode.py
- examples/Backtesting/multi_target.py
- examples/Constraints_Continuous/linear_constraints.py
- examples/Constraints_Discrete/custom_constraints.py
- examples/Constraints_Discrete/dependency_constraints.py
- examples/Constraints_Discrete/mixture_constraints.py
- examples/Constraints_Discrete/prodsum_constraints.py
This PR activates SMOKE_TEST in all of the examples.
Most parameters are set to 2 or 3 when SMOKE_TEST is set. The values chosen when SMOKE_TEST is not being activated are mostly those that were used previously or some slightly larger numbers than 2 or 3 if these were already used previously.
> Include SMOKE_TEST in examples

- CHANGELOG.md
- baybe/constraints/base.py
- baybe/scaler.py
- baybe/utils/dataframe.py
- baybe/utils/interval.py
This is the first part of optimizing torch imports.
All tests passed on my machine with python 3.10 and 3.11.
> Lazy loading torch - part 1

- .github/workflows/docs.yml
This PR downgrades the `upload-pages-artifact` action back to v1.
I tested this version on my fork, where it enabled me to deploy the pages. It is unclear why the deployment does not work for v3 and is something that we will have to look into.
> HOTFIX: Downgrade upload-pages-artifact action to v1

- CHANGELOG.md
- docs/userguide/transfer_learning.md
This is the first draft of a potential user guide for Transfer Learning.
It is probably far from being finished, hence this PR is intended to be a basis for discussions about what the topic should look like. Hence, I decided to already publish this PR rather early, knowing that some members of the team tend to also look at PRs on the weekend ;)
> First draft of Transfer Learning User Guide

- CHANGELOG.md
- baybe/searchspace/discrete.py
- examples/Constraints_Discrete/mixture_constraints.py
- Adds constraints to from_simplex. While the simplex constructor takes care of the overall sum constraint, it was not possible to add other constraints, which is now enabled
- Also fixes a bug in an example not printing the correct asserts in SMOKE_TEST
> Extend `from_simplex` with constraints

- CHANGELOG.md
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- tests/conftest.py
- tests/serialization/test_campaign_serialization.py
Obejct creation form json with the `from_soimplex` constructor has so far been done with the default method which is extensively creating the entire object.
This is ineffective for cartesian-product like search spaces such as made with `from_product` and `from_simplex`
This introduces a separate valdiator for that function. It also consolidates some of the constraint filtering into a small utility.
> Add efficient `from_simplex` validation

- .github/workflows/ci.yml
- .github/workflows/regular.yml
- .github/workflows/release.yml
- CHANGELOG.md
- CONTRIBUTING.md
- baybe/campaign.py
- docs/userguide/transfer_learning.md
- pyproject.toml
- tests/README.md
- tox.ini
(Written by Adrian) Enables Python 3.12 and fixes a bug with the validation converter, which also happens to fix the `cattrs` issue that originally blocked this PR (see details in PR comment).
> Enable Python 3.12

- CHANGELOG.md
- baybe/serialization/core.py
- tests/serialization/test_dataframe_serialization.py
This enables dataframe de-serialziation also from human readable strings instead of only decoded strings
@danielweber90 as per our discussion for BayChem, see the tests for examples
> Enable flexible dataframe de-serialization

- docs/index.md
This PR changes the order of the items in the left sidebar of the documentation.
This is necessary since the current order makes certain items of the sidebar disappear. For testing purposes, this was thus first built and tested on my fork, and the documentation based on this branch can be seen here: https://avhopp.github.io/baybe_dev/
> Change order in sidebar

- CHANGELOG.md
- pyproject.toml
This PR removes the optional `telemetry` group from `pyproject.toml`. The corresponding packages are now directly included without having them as a separate group.
This was necessary since there were problems with installing `baybe` via `poetry` since the `dependencies` contained this explicit dependency. To enable installation with poetry, this was thus changed.
> Remove optional telemetry group

- CHANGELOG.md
- baybe/constraints/base.py
- baybe/objective.py
- baybe/parameters/numerical.py
- baybe/surrogates/custom.py
- baybe/utils/dataframe.py
- baybe/utils/interval.py
- baybe/utils/numerical.py
- baybe/utils/torch.py
As I discussed in the previous PRs we need to import `baybe.utils.numerical` lazily to completely get rid of `torch`.
I didn't touch `surrogates` because it's already fixed in previous PR.
> Lazy load DTypeFloatTorch

- CHANGELOG.md
- baybe/surrogates/gaussian_process.py
fixes inconsistencies treating the `TaskParameter` that could cause errors when the other parts of the searchspace are purely continuous
> Fix: n_task_params now evaluates to 1 if task_idx == 0

- CHANGELOG.md
- baybe/acquisition/partial.py
- baybe/acquisition/utils.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/serialization/mixin.py
- baybe/surrogates/base.py
- baybe/surrogates/custom.py
- baybe/surrogates/gaussian_process.py
- baybe/surrogates/linear.py
- baybe/surrogates/naive.py
- baybe/surrogates/ngboost.py
- baybe/surrogates/random_forest.py
- baybe/surrogates/utils.py
`baybe.utils.numerical` imports torch and still appears in the import hierarchy. I'm going to fix it in another PR.
> Lazy load `torch` in surrogates

- CHANGELOG.md
- baybe/acquisition/__init__.py
- baybe/acquisition/acqfs.py
- baybe/acquisition/adapter.py
- baybe/acquisition/base.py
- baybe/acquisition/partial.py
- baybe/acquisition/utils.py
- baybe/recommenders/base.py
- baybe/recommenders/naive.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/recommenders/pure/bayesian/sequential_greedy.py
- baybe/serialization/core.py
- examples/Backtesting/custom_analytical.py
- examples/Basics/recommenders.py
- examples/Serialization/create_from_config.py
- examples/Serialization/validate_config.py
- tests/conftest.py
- tests/hypothesis_strategies/acquisition.py
- tests/hypothesis_strategies/alternative_creation/test_acquisition.py
- tests/serialization/test_acquisition_serialization.py
- tests/test_acquisition.py
- tests/test_deprecations.py
- tests/test_iterations.py
Included:
- Major changes to the base_unstructuring hook. Whenever a string is provided it will try to find and create a class entry that corresponds to that string either with full name or abbreviation. This only happens for classes that have the `_abbreviation` member, others are unchanged
- Transferred the existing ACQFs, they can be initialized from long-object name, form short object-name, from long-string or from short-string (called abbreviation)
- Deprecated `VarUCB` and `qVarUCB`
- Deprecated `acquisition_function_cls` of ByaesianRecommender and renamed it to `acqf`
- Added hypothesis tests for the existing acquisition functions + one basic test initializing the seqgreedy recommender with these trategies
- renamed internal member `_acquisition_function` in bayesian reocmmenders …
> Acquisition function classes

- CHANGELOG.md
- baybe/objectives/base.py
- baybe/objectives/desirability.py
- baybe/objectives/single.py
- tests/hypothesis_strategies/alternative_creation/test_searchspace.py
- tests/hypothesis_strategies/objectives.py
- tests/hypothesis_strategies/parameters.py
- tests/hypothesis_strategies/targets.py
- tests/hypothesis_strategies/utils.py
- tests/serialization/test_objective_serialization.py
- tests/serialization/test_parameter_serialization.py
- tests/serialization/test_target_serialization.py
- tests/validation/test_objective_validation.py
Adds the hypothesis strategies for our objective classes.
> Hypothesis for objectives

- CHANGELOG.md
- baybe/simulation.py
- baybe/utils/numerical.py
- tests/test_utils.py
Fixes #207 by:
* Correctly accessing `Interval` attributes
* Making `closest_element` handle arbitrary array-like input
> Hotfix for match mode simulation

- CHANGELOG.md
- README.md
- baybe/telemetry.py
- the warning in case telemetry is disabled due to lack of connectivity is only shown to developers. This means most users outside of Merck will not be spammed with this warning anymore as telemetry will always be disabled for them
- Reintroduces telemetry mentioning in the README
> Telemetry changes

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/regular.yml
- CHANGELOG.md
- pyproject.toml
Speedup our environment creation by using `uv` instead of `pip` via `tox-uv`.
The following times were obtained on my local machine by creating environments via `tox --devenv toxenv -e audit-py39` (since `audit` installs all `dev` dependencies):
* tox: 64s
* tox-uv (no cache): 29s
* tox-uv (cached): 4s
> Use tox-uv

- CHANGELOG.md
- baybe/acquisition/__init__.py
- baybe/acquisition/base.py
- baybe/recommenders/naive.py
- baybe/recommenders/pure/bayesian/sequential_greedy.py
- baybe/surrogates/custom.py
- baybe/surrogates/gaussian_process.py
- baybe/surrogates/utils.py
- baybe/utils/dataframe.py
- streamlit/surrogate_models.py
- tests/test_imports.py
- tox.ini
This PR finalizes the import refactoring such that `torch` (and the dependent packages `gpytorch`/`botorch`) are loaded lazily for improved package import speed.
Further, new import tests ensure that:
* all BayBE modules can be loaded without errors
* `torch` is not eagerly loaded (to prevent regressions)
> `torch` lazy loading

- CHANGELOG.md
- baybe/kernels/base.py
- baybe/kernels/basic.py
- baybe/kernels/priors/__init__.py
- baybe/kernels/priors/base.py
- baybe/kernels/priors/basic.py
- baybe/surrogates/gaussian_process.py
- tests/hypothesis_strategies/kernels.py
- tests/hypothesis_strategies/priors.py
- tests/serialization/test_prior_serialization.py
This PR introduces custom priors for kernels. It provides an ABC `Prior` as well as a `GammaPrior` class and corresponding tests.
Note that this PR does not yet introduce custom `ScaleKernels` and only adjusts the priors at the point where they are used for our custom `MaternKernels`. At other parts of the code, we technically still use the original `GPyTorch` priors, which is a bit hidden by the `.to_gyptorch()` call. This will all be fixed in upcoming PRs.
Further note that the kernel serialization currently fails. @AdrianSosic and I already briefly investigated the error and did not manage to track it down, and agreed to investigate this issue once the code is pushed (which is the case now)
> Custom kernel priors

- CHANGELOG.md
- baybe/acquisition/acqfs.py
- baybe/acquisition/base.py
- baybe/exceptions.py
- baybe/objectives/base.py
- baybe/objectives/deprecation.py
- baybe/serialization/core.py
- baybe/utils/basic.py
- docs/userguide/campaigns.md
- docs/userguide/serialization.md
- docs/userguide/userguide.md
- tests/docs/utils.py
- tests/hypothesis_strategies/alternative_creation/test_acquisition.py
- tests/serialization/test_deserialization.py
- tests/test_iterations.py
This PR finally adds a serialization user guide and fixes a few little issues in the serialization logic:
* Structuring concrete subclasses no longer requires providing an explicit `type` field
* The `_target(s)` attributes of objectives in are unstructured without the underscore
(this is currently done via a workaround by overriding the hook of the base class)
> Serialization user guide

- baybe/recommenders/pure/nonpredictive/clustering.py
- baybe/surrogates/__init__.py
- baybe/surrogates/base.py
- baybe/surrogates/custom.py
- baybe/surrogates/gaussian_process.py
- baybe/surrogates/linear.py
- baybe/surrogates/naive.py
- baybe/surrogates/ngboost.py
- baybe/surrogates/random_forest.py
- baybe/surrogates/utils.py
- docs/conf.py
- docs/userguide/surrogates.md
- examples/Basics/recommenders.py
- streamlit/surrogate_models.py
- tests/serialization/test_surrogate_serialization.py
- tests/test_iterations.py
This PR refactors our surrogate package, which significantly removes boilerplate/workaround code and solves several longstanding issues:
* The `catch_constant_targets` and `scale_model` decorators have been drastically reduced/improved. Most importantly, they no longer cause problems in the subclass hierarchy, which allows us to remove many ugly workarounds with serialization hooks, the docs, typing, ... 
**Note:** Potentially the `scale_model` decorator might vanish entirely when refactoring scaling, but this already serves as a preparation as the decorator can now be cleanly removed without other side-effects.
* The corresponding code and doc workarounds have been fixed
* ~~The `_model` attribute has been pulled up the base class and is now correctly handled in serialization and …
> Refactor surrogates and decorators

- .github/workflows/docs.yml
- docs/conf.py
- docs/scripts/convert_code_to_documentation.py
This PR simplifies our current doc building script. The only goal of this PR is to get rid of code that is actually not necessary and that makes the script unnecessarily complex.
More precisely, this PR does the following:
- Change the default location of the documentation: This is done as it potentially allows easier local building and testing in the future.
- Remove the option to include private members in the documentation: This was not used at all but was responsible for quite some amount of code
- Do not delete the directories created by Sphinx: Sphinx creates several directories while building the documentation. These were deleted previously, which this PR now changes.
Note that there is exactly one commit per change, trying to make this as easy to review as possible. Also, you can …
> Simplification of doc building script

- CHANGELOG.md
- baybe/telemetry.py
- tests/simulate_telemetry.py
This fixes #233 in that iT moves some code parts that have been executed even if telemetry was disabled (and thus could fail).
It doesn't touch the suggested replacement of `requests` because a confirmation with the UPTIMIZE Sagemaker kernels would be required, which in itself requires an update of the Sagemaker<->baybe connection due to the Python 3.8 deprecation
> Fix telemetry execution

- CHANGELOG.md
- baybe/kernels/__init__.py
- baybe/kernels/base.py
- baybe/kernels/basic.py
- baybe/surrogates/gaussian_process.py
- baybe/utils/basic.py
- baybe/utils/conversion.py
- tests/hypothesis_strategies/kernels.py
- tests/serialization/test_kernel_serialization.py
- tests/test_iterations.py
This PR introduces custom ScaleKernels. It is currently based on #219 and will be properly rebased and moved out of draft state once that PR is merged.
> Include custom `ScaleKernel`

- tests/conftest.py
About 30-50% of pipelines fail because there is a hypothesis timeout. This PR introduces a CI profile that
- increases the hypothesis deadline form 200ms to 500ms
- doubles the amount of max examples (default of 100 seemed a bit small)
> Increate hypothesis deadline

- CHANGELOG.md
- baybe/simulation/core.py
- baybe/simulation/scenarios.py
- baybe/utils/basic.py
- baybe/utils/random.py
This PR fixes #218 by adding a context manager that allows running simulations without altering the state of the global random number generators.
> Avoid altering RNG states

- CHANGELOG.md
- baybe/constraints/validation.py
- baybe/parameters/base.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- baybe/utils/dataframe.py
- baybe/utils/memory.py
- tests/test_utils.py
Closes #223 
Added
- utility to convert a float number indicating the byte size of an object into a human readable format with unit
- utility to estimate upper bound for discrete `exp_rep` and `comp_rep` of the searchspace based on a list of parameters
- `is_discrete` and `is_continuous` properties for the Parameter base class indicating whether they are conti or discrete (similar to already existing props for constraints)
Test
- used the searchspace from full_lookup in three size variants (by adding values to the temperature parameter)
> Memory estimation utilities

- CHANGELOG.md
- baybe/kernels/__init__.py
- baybe/kernels/basic.py
- baybe/kernels/composite.py
- baybe/priors/__init__.py
- tests/hypothesis_strategies/kernels.py
- tests/test_iterations.py
This PR is adding more kernel choices. There are some notable points to consider below:
**Bugfix arithmetic Kernels**
These used to apply operators like `mul(*a_list)` but since the operators are defined as 2-input only this failed for a 3-composite kernel test I added. It was fixed via rephrasing it to `reduce(mul, a_list)`
**Removed Prior Iteration Tests**
These have become obsolete as the kernels are tested with many priors. I've also reduced the prior used with the scale kernel in iteration tests to one choice, otherwise the list of kernels just got too large.
**RQKernel alpha**
Even though this kernel has an attribute called `alpha` (also visible in the equation [here](https://docs.gpytorch.ai/en/stable/kernels.html#rqkernel)) it does not seem to accept priors for it. Hence, I have …
> Add more kernels

- docs/scripts/convert_code_to_documentation.py
- docs/scripts/utils.py
This PR fixes the incorrectly displayed picture in the README which was not adjusted when changing between light and dark mode.
Please build the documentation locally to verify since this has no influence on the github version.
> Fix wrong picture in README

- CHANGELOG.md
- baybe/surrogates/base.py
Non GP surrogate models could experience problems with `deepcopy` and the simulation module because they were non-slotted but the base class was slotted. This removes the base class slots.
> Fix surrogate slots

- CHANGELOG.md
- baybe/constraints/base.py
- baybe/constraints/conditions.py
- baybe/objectives/desirability.py
- baybe/parameters/base.py
- baybe/parameters/categorical.py
- baybe/parameters/custom.py
- baybe/parameters/numerical.py
- baybe/parameters/substance.py
- baybe/simulation/core.py
- baybe/simulation/lookup.py
- baybe/utils/chemistry.py
- baybe/utils/memory.py
- tests/conftest.py
- tests/hypothesis_strategies/acquisition.py
- tests/hypothesis_strategies/basic.py
- tests/hypothesis_strategies/constraints.py
- tests/hypothesis_strategies/dataframes.py
- tests/hypothesis_strategies/objectives.py
- tests/hypothesis_strategies/parameters.py
- tests/test_searchspace.py
- tests/validation/test_objective_validation.py
- tests/validation/test_parameter_validation.py
- tox.ini
Since floating point precision can be controlled via env vars (#226) various problems have surfaced letting tests fail in single precision.
This PR fixes those. They were mostly related to the way `values` and `comp_df` were created for parameters, `selection` was treated in `SubSelectionCondition` and a `lookup` in a different float precision being used in a simulation.
The only remaining issues with test in single precision are numerical instabilities (out of scope)
> Fix dtypes related to floating point precision

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/regular.yml
- CHANGELOG.md
- baybe/utils/interval.py
- pyproject.toml
- tests/README.md
- tox.ini
This PR drops Python 3.9 support because Botorch, being one of our main dependencies, follows the "Scientific Python" guidelines and thus no longer supports it:
https://scientific-python.org/specs/spec-0000/
> Drop Python 3.9

- CHANGELOG.md
- baybe/campaign.py
- baybe/recommenders/base.py
- baybe/recommenders/meta/base.py
- baybe/recommenders/meta/sequential.py
- baybe/recommenders/naive.py
- baybe/recommenders/pure/base.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/recommenders/pure/nonpredictive/base.py
- baybe/simulation/core.py
- examples/Multi_Target/desirability.py
- mypy.ini
- tests/conftest.py
- tests/serialization/test_campaign_serialization.py
- tests/test_deprecations.py
- tests/test_integration.py
This PR implements a breaking change by refactoring the recommender signature such that:
* it accepts an optional `Objective`
* it expects training data as a single dataframe in experimental representation
Apart from fixing certain responsibilities (e.g. `Campaign` now only acts as a meta-data handler, just like it is supposed to) this enables/prepares several new features:
* Users can directly use `Recommender`s as entry point instead of being forced to go via `Campaign`
* Because recommenders now operate on experimental representations, they can offer the same interface back to users, e.g. when exposing model-internal things such as acquisition functions and surrogate models
* Additional pre-processing steps that require access to the experimental representation (such as …
> Refactor recommender signature

- CHANGELOG.md
- baybe/campaign.py
- baybe/recommenders/base.py
- tests/conftest.py
- tests/test_deprecations.py
This PR adds the missing validators to the Campaign attributes ~~and freezes the searchspace/objective attributes~~.
> Campaign validators

- baybe/_optional/info.py
- pyproject.toml
- tox.ini
Fixes the `PRE_COMMIT_INSTALLED` and `TYPOS_INSTALLED` flags (the latter using a workaround) and adds the `pytest-error-for-skips` plugin to disallow test skips in FULLTEST environment.
> Fix optional dependency flags

- CHANGELOG.md
- baybe/utils/basic.py
- examples/Custom_Hooks/Custom_Hooks_Header.md
- examples/Custom_Hooks/callable.py
- tests/test_utils.py
This PR implements the first version of the `register_hook` utility with a simple example.
Please note: no big reviewing effort is required since these changes were already approved on #247 .
> Register hook with the same signature

- .github/workflows/ci.yml
- .github/workflows/regular.yml
lets try to fix the coretest issues we face regularly by removing the caching for these tox envs
I think it will add between 30 and 60s to an execution time of about 6,5 min, so not terrible and still shorter than the fulltests which run in parallel
> Remove core test caching

- .pre-commit-config.yaml
- pydoclint.toml
- pyproject.toml
Workaround to avoid attrs incompatibility. For details, see: https://github.com/jsh9/pydoclint/issues/140
> Fix attrs incompatibility of pydoclint

- CHANGELOG.md
- baybe/campaign.py
- baybe/parameters/base.py
- baybe/parameters/categorical.py
- baybe/parameters/custom.py
- baybe/parameters/numerical.py
- baybe/parameters/substance.py
- baybe/utils/dataframe.py
- tests/test_deprecations.py
For naming consistency, `is_numeric` gets replaced with `is_numerical`.
> Replace `is_numeric` class attribute with `is_numerical`

- .github/workflows/ci.yml
- .github/workflows/regular.yml
- CHANGELOG.md
- baybe/recommenders/pure/nonpredictive/clustering.py
Due to continuing serialization problems that were thought to be related with caching, #277 deactivated core test caching and #294 was prepared to do the same for the full test environment.
This PR reactivates caching and instead refactors the class layout of `SKLearnClusteringRecommender` in an attempt to fix the root cause. Mysteriously, the top-level import of `sklearn.mixture.GaussianMixture` seems to cause trouble. While the reason is still unclear, turning it into a lazy import (which will also become handy later when making `scikit-learn` an optional dependency) seems to resolve the problem.
On a side note: deactivating slots for the recommenders solves the problem as well, which suggests that the root cause could be related to classes not being properly garbage collected (since …
> Fix serialization and caching

- CHANGELOG.md
- baybe/parameters/base.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/searchspace/continuous.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- baybe/searchspace/validation.py
- tests/test_deprecations.py
- tests/validation/test_searchspace_validation.py
The behavior of the search space `transform` methods was not very precise and invalid input was not caught appropriately.
This PR makes the following changes:
* The dataframe to be transformed must now be passed as positional argument. This avoids explicit use of the somewhat unclear argument name "data".
* Which columns the dataframe may or may not contain is now clearly controlled through new boolean flags added as keyword-only arguments.
* The docstrings of all methods are reworked and centrally maintained in the `SearchSpace` class, with references in subspace classes.
* All changes are made backward-compatible through a deprecation mechanism.
* Both test for the new logic and the deprecation are in place.
* Renames `DiscreteParameter.transform_rep_exp2comp` to `transform` and …
> Refactor search space `transform` methods

- CHANGELOG.md
- baybe/acquisition/base.py
- baybe/exceptions.py
- baybe/recommenders/naive.py
- baybe/recommenders/pure/base.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/recommenders/pure/bayesian/botorch.py
- baybe/recommenders/pure/nonpredictive/clustering.py
- baybe/recommenders/pure/nonpredictive/sampling.py
- baybe/surrogates/base.py
- baybe/surrogates/utils.py
This PR is a first step toward a refactored `Surrogate` layout:
* It moves the `exp_rep`-to-`comp_rep` transition point into the surrogates, which now become responsible for handling the transformation and can do it in whatever way they need it (which will also simplify scaling later on).
* This cleans up the interface because users / calling classes can now pass data in its canonical form (i.e., `exp_rep`) and do not need to worry about transformations.
* This also means we can easily expose the trained surrogates to users for model inspection (e.g., feature importance).
> Comp Rep Transition Point

- CHANGELOG.md
- baybe/exceptions.py
- baybe/recommenders/meta/base.py
- baybe/recommenders/pure/nonpredictive/base.py
- tests/test_iterations.py
Adjustments to avoid annoying warnings
- `MetaRecommender`s do not use `objective` and `measurements` arguments with `NonPredictiveRecommender`s anymore --> source of the warnings flood in many simulations
- Added a custom warning to distinguish the non-predictive recommender warnings
- Caught some expected warnings in tests
> Fix MetaRecommender Warnings

- baybe/acquisition/acqfs.py
- baybe/recommenders/pure/bayesian/base.py
There have been two instances of internal calls of deprecated functionality, causing unintended deprecation calls
- random recommedner called `samples_random`
- transformation of measurements did not explicitly set `allow_extra=True`
> Fix Deprecated Calls

- CHANGELOG.md
- baybe/constraints/base.py
- baybe/constraints/conditions.py
- baybe/constraints/discrete.py
- baybe/searchspace/discrete.py
- docs/conf.py
- mypy.ini
- pyproject.toml
- tests/test_constraints_discrete.py
- tests/test_constraints_polars.py
**Update:  Added Polars support for `DiscreteExclusionConstraint`**
As the title says.
Tiny modifications are on the way, like removing the list of `polars_friendly_constraints`.
> Polars pipeline for discrete sum, product and exclusion constraints

- CHANGELOG.md
- baybe/simulation/_imputation.py
- baybe/simulation/core.py
- baybe/simulation/lookup.py
- baybe/utils/basic.py
- baybe/utils/dataframe.py
- examples/Basics/campaign.py
- examples/Basics/recommenders.py
- examples/Constraints_Discrete/custom_constraints.py
- examples/Constraints_Discrete/dependency_constraints.py
- examples/Constraints_Discrete/exclusion_constraints.py
- examples/Constraints_Discrete/mixture_constraints.py
- examples/Constraints_Discrete/prodsum_constraints.py
- examples/Custom_Surrogates/custom_architecture_sklearn.py
- examples/Custom_Surrogates/custom_architecture_torch.py
- examples/Custom_Surrogates/custom_pretrained.py
- examples/Custom_Surrogates/surrogate_params.py
- examples/Multi_Target/desirability.py
- pytest.ini
- tests/conftest.py
- tests/simulate_telemetry.py
- tests/test_input_output.py
This PR is another step toward a cleaned simulation package:
* Decouples the lookup mechanism from `Campaign` so that it can be flexibly used without having to set up a campaign object first (e.g. in tests)
* Splits up the monolithic lookup function into different cases
* Rewrites the docstrings and activates doctests
* ~~Moves simulation-related utilities to the simulation package~~
> Reorganize simulation lookup

- CHANGELOG.md
- baybe/utils/plotting.py
- examples/Backtesting/botorch_analytical.py
- examples/Backtesting/full_lookup.py
- examples/Transfer_Learning/backtesting.py
- examples/Transfer_Learning/basic_transfer_learning.py
This PR changes the path for saving the results from `sys.path[0]` to `"."`.
As far as I understand, this has the consequence of the images being created in the directory from which `python` is being called, and I added a corresponding explanation at the corresponding positions.
Note that this change should not have any influence on the shown images: The tests that I did on my fork showed that the static images that we insert manually into the jupyter notebooks are still correctly inserted, even with this change.
> Change path from sys.path[0] to .

- CHANGELOG.md
- baybe/campaign.py
- baybe/parameters/base.py
- baybe/searchspace/continuous.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
This PR brings new `to_searchspace`, `to_subspace`, `from_parameter` and `from_product` convenience constructors, and enables search space autoconversion in the `Campaign` class, for improved user experience. A main improvement is that they allow to avoid the common pattern `Searchspace.from_product([parameter])`, which was so far the only way to specify a one-dimensional search space and was rather confusing for the user since there is effectively no product involved.
> Searchspace convenience constructors

- CHANGELOG.md
- baybe/acquisition/__init__.py
- baybe/acquisition/acqfs.py
- pyproject.toml
- tests/hypothesis_strategies/acquisition.py
- tests/test_iterations.py
- tox.ini
- adds `qKnowledgeGradient` aka `qKG` to the list of supported acqfs
- the limit of `num_fantasies` is set to max of `512` in the hypothesis test as it seems to be a fairly expensive acqf from an initial trial
- Skips for some iteration tests have been added because `qKG` does not work with discrete optimization
> Add KnowledgeGradient ACQF

- CHANGELOG.md
- baybe/surrogates/_adapter.py
- baybe/surrogates/base.py
- baybe/surrogates/custom.py
- baybe/surrogates/gaussian_process/core.py
- baybe/surrogates/linear.py
- baybe/surrogates/naive.py
- baybe/surrogates/ngboost.py
- baybe/surrogates/random_forest.py
- baybe/surrogates/utils.py
This PR is a next step toward a lean surrogate class layout:
* `Surrogate.(_)posterior` now returns a `Posterior` object
* `Surrogate._fit` no longer expects the `SearchSpace` as an argument, which brings us closer to the state that `.fit` and `.posterior` operate on the user/dataframe/context-level while `_posterior` and `_fit` operate on the purely mathematical level. This means that a user who writes their own surrogate class effectively only needs to implement the corresponding mathematical model in the latter two methods. Optional context information that may be required for this implementation (like the dimension index of the `TaskParameter` in the passed `Tensor` object) is now encapsulated into a surrogate-specific `context` object, that can be arbitrarily populated by the …
> Surrogate Posteriors

- CHANGELOG.md
- baybe/constraints/base.py
- baybe/constraints/discrete.py
- baybe/searchspace/continuous.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- baybe/utils/augmentation.py
- tests/test_utils.py
- tests/utils/test_augmentation.py
- tests/utils/test_basic.py
- tests/utils/test_memory.py
- tests/utils/test_numerical.py
- tests/utils/test_sampling_algorithms.py
Adds utilities for data augmentation and small modifications to constraints:
- dataframe based utilities `df_apply_permutation_augmentation` and `df_apply_dependency_augmentation` + tests
- Constraints have the new `eval_during_augmentation` flag
These will be useful for upcoming PRs on `add_measurements` allowing inputs affected by constraints (@Scienfitz) and data augmentation of measurements (@mhrmsn)
The example are rendered in the doc like:
> Augmentation Utilities

- CHANGELOG.md
- baybe/acquisition/acqfs.py
- baybe/acquisition/base.py
- baybe/exceptions.py
- baybe/kernels/base.py
- baybe/kernels/basic.py
- baybe/kernels/composite.py
- baybe/priors/base.py
- baybe/utils/basic.py
- examples/Custom_Surrogates/custom_architecture_torch.py
- ruff.toml
- tests/hypothesis_strategies/basic.py
- tests/hypothesis_strategies/kernels.py
- tests/test_kernels.py
- tests/validation/kernels/test_basic_kernel_validation.py
- tests/validation/kernels/test_composite_kernel_validation.py
This PR fixes one of the two issues that caused transfer learning performance to deteriorate, fixing several other issues along the way.
* Main issue fixed: the arguments provided to `to_gpytorch` (e.g. `ard_num_dims`) were not passed on to the GPyTorch kernel class.
* The `to_gpytorch` call was not tested and did in fact not succeed in all cases. Causing issues:
* Hypothesis strategies did not account for positive-valued attributes, and no validators where in place. --> fixed
* ~~The torch dtype was not correctly set when translating priors to GPyTorch. --> fixed using temporary workaround (see below)~~
* ~~A proper solution to setting the default torch dtype requires overriding the torch import mechanism using `importlib`s machinery, due to lazy loading. A preliminary workaround is …
> Fix kernel translation

- CHANGELOG.md
- baybe/simulation/scenarios.py
- ignore `UnusedObjectWarning` caused by recommenders in simulations
- this was caused for isntance by using the `RandomRecommender`, a common use case because its a baseline
- I tried to use warning action modes `once` and `module` but that didnt work at all
> Ignore `UnusedObjectWarning` caused by nonpred recommenders in simulation

- CHANGELOG.md
- baybe/surrogates/gaussian_process/core.py
use torch fitting with 100 steps again until we finetune this better
here some pictures with the new fit indicating previous results are there again
tobis notebook with this PR
vs old (non torch) fitting
> Restore old MLL fit

- CHANGELOG.md
- baybe/acquisition/acqfs.py
- baybe/recommenders/pure/bayesian/base.py
This PR ~maps the regular "EI" acquisition functions to their "log" versions~ changes the default acquisition function from `qEI` to `qLogEI`, which improves numerical stability and also avoids the warning thrown in `botorch>=0.11.3`.
> Switch to log-acqfs

- README.md
- baybe/_optional/info.py
- baybe/_optional/polars.py
- baybe/constraints/base.py
- baybe/constraints/conditions.py
- baybe/constraints/discrete.py
- baybe/searchspace/discrete.py
- docs/userguide/envvars.md
- pyproject.toml
- tests/test_constraints_polars.py
- tox.ini
based on #306 
- make `polars` optional dependency
- reworked `Constraint.to_polars` into `Constraint.get_invalid_polars` to make it consistent with the pandas version
- skipped optional tests
> Make Polars Optional

- docs/index.md
This PR rearranges the elements in the doc sidebar for the upcoming release:
* Groups all documentation related entries (README, User Guide, Examples, API Reference) under one common heading
* Lists these items at the top (since most relevant for the average user)
* Groups the remaining items under second heading
Rendered doc on my fork:
https://adriansosic.github.io/baybe-dev/
> Rearrange TOC in sidebar

- CHANGELOG.md
- baybe/simulation/scenarios.py
- examples/Custom_Hooks/campaign_stopping.py
- examples/Custom_Hooks/probability_of_improvement.py
Example is based on checking that at leat 10% of candidates have a PI of at least 1%
The hook is attached to the entire class becasue `simulate_*` involves deepcopies that cause hooks to be ignored
> Add Example for Dynamic Campaign Stopping

- CHANGELOG.md
- baybe/surrogates/gaussian_process/core.py
Transfer learning using the `scipy` solver invoked via `fit_gpytorch_mll` is currently unstable because it seems we run into overfitting problems due to missing priors on the involved `IndexKernel`. Using the old `fit_gpytorch_mll_torch` routine mitigates this problem, probably because the MLL fitting does not fully converge, which effectively acts as regularization via early stopping. In a non-transfer-learning context, however, the `scipy` solver produces generally better results.
This PR thus implements a temporary workaround where the solver is chosen adaptively based on the presence of a `TaskParameter`.
> Conditional solver selection

- CHANGELOG.md
- baybe/acquisition/acqfs.py
- baybe/acquisition/base.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/recommenders/pure/bayesian/botorch.py
- baybe/searchspace/core.py
- baybe/surrogates/_adapter.py
- baybe/surrogates/base.py
- baybe/surrogates/custom.py
- baybe/surrogates/gaussian_process/core.py
- baybe/surrogates/ngboost.py
- baybe/surrogates/random_forest.py
- baybe/utils/scaling.py
- tests/test_scaling.py
PR #315 introduced the new configurable class-based scaling approach, but:
* did so using some rather heavy hierarchy of methods
* introduced a conceptual bug in that the scaling logic was not consistently applied in the correct way (e.g. `best_f` should not have been scaled)
* the resulting layout implied a rather unclear interface for a `SurrogateProtocol`, where users providing such protocols would also need to expose transform related methods that should actually stay surrogate internal.
This PR refactors scaling mechanism with the final interfaces in mind, in particular the newly introduced `SurrogateProtocol` class.
* Much of the transform-related machinery was removed. Left are only two scaler attributes (one for input, one for output) which are purely class internal.
* The result …
> Surrogate interface

- CHANGELOG.md
Adds a `py.typed` file to enable the use of type checkers on the user side.
Before:
After:
> Add py.typed

- .lockfiles/py310-dev.lock
- CHANGELOG.md
- baybe/parameters/categorical.py
- baybe/parameters/numerical.py
- baybe/utils/conversion.py
- pyproject.toml
- tests/validation/test_parameter_validation.py
Fixes #171 using the new 3-argument converters available in `attrs==0.24.1`.
> Fix parameter value conversion

- CHANGELOG.md
- baybe/utils/sampling_algorithms.py
- tests/utils/test_sampling_algorithms.py
Working on the `0.10.0` release, it was noticed that the optimization results can depend on the order of substances provided by the user if a `SubstanceParameter` is involved. While the problem is still partly open (see #341), investigation showed that also the `FPSRecommender` can yield different results when provided the same set of points in a different order.
This PR improves the FPS code in that:
* It adds proper input validation
* Makes the algorithm agnostic to permutations of the input
* Adds a thorough hypothesis test to verify the FPS property and permutation-invariance
* Properly handles edge cases involving duplicated points
* Improves the documentation
> Improve FPS

- baybe/campaign.py
- baybe/objectives/desirability.py
- baybe/objectives/single.py
- mypy.ini
With `cattrs==24.1.0` released, we suddenly get more `type-abstract` errors. Since these are basically false positives, this PR globally disables the warnings. References are provided in `mypy.ini`.
> Silence mypy type-abstract errors

- CHANGELOG.md
- baybe/acquisition/base.py
- baybe/targets/numerical.py
- streamlit/surrogate_models.py
This PR changes the behavior of `NumericalTarget` in `MIN` mode in that the minimization is lo longer implement by negating the computational representation of the target but placing an objective on the acquisition function.
This approach avoids the problem that otherwise the surrogate would be trained on inverted targets, resulting in inverted predictions, which prevents us from exposing the surrogate as-is to the user. Also, it cleanly separates the objective (i.e. "minimization") from the target representation.
> `MIN` mode via acquisition function

- CHANGELOG.md
- baybe/exceptions.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/surrogates/base.py
- baybe/surrogates/custom.py
- baybe/surrogates/gaussian_process/core.py
- baybe/surrogates/linear.py
- baybe/surrogates/naive.py
- baybe/surrogates/ngboost.py
- baybe/surrogates/random_forest.py
- baybe/surrogates/utils.py
- examples/Custom_Surrogates/custom_pretrained.py
- examples/Custom_Surrogates/surrogate_params.py
- streamlit/surrogate_models.py
- tests/test_iterations.py
When the non-GP surrogates where added, they were not designed with batch recommendations in mind. Now that batch recommendations can be generally requested, surrogate models providing only marginal posterior information yield unusable results for batch sizes larger than one.
This PR fixes the issue by:
* Making the `RandomForestSurrogate` produce a proper `EnsemblePosterior` that is capable of expressing covariance structure, which is the basic requirement for batch prediction
* Disallowing batch sizes larger than one for surrogates that only provide marginal posteriors
> Fix batch recommendation

- CHANGELOG.md
- baybe/parameters/categorical.py
- baybe/parameters/substance.py
- baybe/parameters/utils.py
- baybe/searchspace/continuous.py
- baybe/searchspace/discrete.py
- examples/Custom_Hooks/campaign_stopping.py
- tests/hypothesis_strategies/alternative_creation/test_searchspace.py
- tests/test_searchspace.py
This PR adds code to:
* sort the user-provided values before storing them as attributes in discrete parameters (see also #336)
* sort the parameters stored in search spaces
If unsorted, this can cause problems with reproducibility in the sense that the same parameter content provided in a different order can lead to different optimization results. For instance, the `RandomRecommender` randomly selects rows from the `comp_rep` dataframe for the discrete subspace, which will be ordered differently if the parameter values come
in a different order. This can lead to rather surprising behavior, like in situations when the parameter values are given as the output of Python's `set` function, whose order depends on `PYTHONHASHSEED`.
> Parameter permutation

- CHANGELOG.md
- baybe/acquisition/base.py
This PR makes improvement-based acquisition functions consider the maximum posterior mean instead of the maximum noisy measurement as reference value. There are several motivations for this:
* While a matter of definition, it seems there is slight consensus for defining the improvement like this (even though I have to say I'm surprised how few sources are actually explicit about it).
* It's in line with what we'd get if we used botorch's acquisition function factory
* It solves the problem that otherwise the improvement in random forest models would be zero (theoretical value) and vanishingly small for the botorch functions (which internally use smooth approximations, e.g. sigmoid for computing the probability of improvement based on Monte Carlo samples).
As sanity check, basic lookup …
> Best_f from posterior means

- CHANGELOG.md
- baybe/campaign.py
- baybe/searchspace/discrete.py
- tests/hypothesis_strategies/alternative_creation/test_searchspace.py
Fixes #358 by:
* Catching the edge case when a degenerate dataframe with no columns is provided
* Updating the meta data only when discrete subspace is present (not required for the bugfix but still to be changed)
> Fix `SubspaceDiscrete.from_dataframe` edge case

- baybe/campaign.py
- baybe/objectives/desirability.py
- baybe/objectives/single.py
- baybe/parameters/numerical.py
- baybe/recommenders/meta/sequential.py
- baybe/recommenders/pure/bayesian/botorch.py
- baybe/recommenders/pure/nonpredictive/clustering.py
- baybe/recommenders/pure/nonpredictive/sampling.py
- baybe/searchspace/continuous.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- baybe/surrogates/bandit.py
- baybe/surrogates/base.py
- baybe/surrogates/custom.py
- baybe/surrogates/gaussian_process/core.py
- baybe/surrogates/linear.py
- baybe/surrogates/ngboost.py
- baybe/surrogates/random_forest.py
- baybe/utils/dataframe.py
- baybe/utils/plotting.py
- examples/Basics/recommenders.py
- examples/Constraints_Continuous/hybrid_space.py
- examples/Constraints_Continuous/linear_constraints.py
- examples/Searchspaces/continuous_space_botorch_function.py
- examples/Serialization/basic_serialization.py
- examples/Serialization/create_from_config.py
- examples/Serialization/validate_config.py
This PR fixes all of the visual issues that we currently have in the examples. This includes
- Fixing deprecated mechanisms that were still being used
- Changing the format of of `__str__` representations to avoid messing up when converting to notebook
- Adding several missing `__str__` representations
- Adding an `indent` function for indentation within `__str__` representations.
To verify, just build the documentation locally and go through the examples.
> Fix visuals in examples

- CHANGELOG.md
- baybe/recommenders/pure/bayesian/botorch.py
- tests/test_input_output.py
Fixes #353 
Unintended reordering of discrete search space parts in `BotorchRecommender` was caused during pd.merging by the searchspace being on the left, however it should be on the right and the merge is safest done with `how='left'` while having the numerical points returned by botorch on the left -> the resulting rows will follow their order.
A test has been written, perhaps though a little too complicated but anyhow. We can construct a searchspace/target construct where it would be expected that the order of the searchspace is strongly broken when getting recommendations (although I havent been able to create one that is exactly anti-ordered). In the faulty variant the recommendation order would still be monotonically increasing like in the searchspace, while the "correct" order is …
> Fix Recommendation Order for BotorchRecommender

- .lockfiles/py310-dev.lock
- CHANGELOG.md
- baybe/campaign.py
- baybe/recommenders/base.py
- baybe/recommenders/meta/base.py
- baybe/recommenders/pure/base.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/serialization/core.py
- baybe/serialization/mixin.py
- baybe/surrogates/base.py
- mypy.ini
- pyproject.toml
- tests/test_deprecations.py
- tests/test_surrogate.py
This PR enables convenient access to the surrogate model and posterior predictive distribution via the `Campaign` class.
> Expose surrogate

- examples/Multi_Armed_Bandit/bernoulli_multi_armed_bandit.py
This PR reduces the runtime of the Bernoulli multi-armed bandit example from about 55 seconds to 7 seconds (in SMOKE_TEST setting) and sets a random seed for reproducibility.
This is supposed to improve the displayed results in the example which were unconverged and didnt show the discussed trend.
> Speedup Bernoulli Multi-Armed Bandit Example

- docs/conf.py
This PR fixes the incorrect link for retrieving the documentation parts of `torch`. It seems like they have just switched their naming from `master` to `main`, requiring us to fix the link that we use.
> Fix intersphinx link for torch

- CHANGELOG.md
- baybe/searchspace/core.py
Fixes #352 
Now
- retrieves the parameter object belonging to the requested name
- then exact-matches column names in the comp_rep to the ones of the parameter via its `comp_rep_columns`
> Fix Name Matching for Retrieving Comp Rep Indices

- CHANGELOG.md
- baybe/campaign.py
- docs/userguide/surrogates.md
- tests/test_campaign.py
Fixes #385 
- enables the extraction of surrogates for transformed single targets or desirability objects
- adds a few tests
- mentions `get_surrogate` in the user guide
> Remove `get_surrogate` Restrictions

- CHANGELOG.md
- baybe/constraints/__init__.py
- baybe/constraints/base.py
- baybe/constraints/continuous.py
- baybe/constraints/deprecation.py
- baybe/searchspace/continuous.py
- docs/userguide/constraints.md
- examples/Backtesting/multi_target.py
- examples/Constraints_Continuous/hybrid_space.py
- examples/Constraints_Continuous/linear_constraints.py
- tests/conftest.py
- tests/constraints/test_cardinality_constraint_continuous.py
- tests/constraints/test_constraints_continuous.py
- tests/hypothesis_strategies/constraints.py
- tests/serialization/test_constraint_serialization.py
- tests/test_deprecations.py
- tests/test_searchspace.py
This PR introduces unite the three previous linear continuous constraints in a new class called `ContinuousLinearConstraint`. The equation behavior (equality or one of the inequalities) is now ontrolled via the `operator` keyword
This is required for currently ongoing updates on BayChem, ideally we can publish this as part of a new version `0.11.1`
> Consolidate Continuous Linear Constraints

- CHANGELOG.md
- baybe/recommenders/pure/bayesian/botorch.py
- docs/userguide/recommenders.md
BotorchRecommender now has the optional keywords `n_restarts` and `n_raw_samples` which control continuous optimization behavior and can be increased if the user desires. The defaults have been slighlty increased as well as previous values seemed extremely low.
> Add Continuous Optimization Controls to BotorchRecommender

- CHANGELOG.md
- baybe/simulation/lookup.py
- baybe/utils/dataframe.py
- docs/userguide/async.md
- docs/userguide/userguide.md
- docs/userguide/utils.md
- examples/Basics/campaign.py
- examples/Basics/recommenders.py
- examples/Constraints_Discrete/custom_constraints.py
- examples/Constraints_Discrete/dependency_constraints.py
- examples/Constraints_Discrete/exclusion_constraints.py
- examples/Constraints_Discrete/mixture_constraints.py
- examples/Constraints_Discrete/prodsum_constraints.py
- examples/Custom_Surrogates/custom_pretrained.py
- examples/Custom_Surrogates/surrogate_params.py
- examples/Multi_Target/desirability.py
- tests/conftest.py
- tests/docs/test_docs.py
- tests/simulate_telemetry.py
- tests/test_input_output.py
- tests/test_pending_experiments.py
- tests/test_surrogate.py
Adds explanations for these utilities:
- estimate discrete space memory size
- control reproducibility via random seeds
- adding fake targets and parameter noise
Note: This required some adjustment of the code execution test. It seems that list comprehensions called via `exec` have some weird scope, causing `NameError` for `NumericalDiscreteParameter` even though it was imported int he code block. So I am now providing a custom dict as globals and locals arg to `exec` which seems to unify the scopes. As far as I know this should still maintain isolation between separately tested code blocks.
> Add Explanation of some Utilities to User Guide

- baybe/constraints/base.py
This PR fixes one of the issues from #195 by changing the docstring.
Current:
New:
> Fix math in  CardinalityConstraint docstring

- .lockfiles/py310-dev.lock
- pyproject.toml
to fix pip-audit vulnerabilities
```terminal
audit-py310: commands[1]> pip-audit
\ Auditing lifelinesFound 2 known vulnerabilities in 1 package
Name      Version ID                  Fix Versions
--------- ------- ------------------- ------------
streamlit 1.22.0  GHSA-8qw9-gf7w-42x5 1.30.0
streamlit 1.22.0  GHSA-rxff-vr5r-8cj5 1.37.0
```
> Bump Streamlit Requirement

- CHANGELOG.md
- baybe/objectives/base.py
- baybe/objectives/desirability.py
- baybe/objectives/single.py
- baybe/searchspace/continuous.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- baybe/searchspace/validation.py
- baybe/surrogates/base.py
- baybe/utils/dataframe.py
- baybe/utils/validation.py
- examples/Multi_Target/desirability.py
- tests/test_deprecations.py
- tests/validation/test_searchspace_validation.py
Improves the `Objective.transform` interface and introduces explicit column validation, similar to what has been done for search spaces in #289.
> Refactor objective transform interface

- .lockfiles/py310-dev.lock
- .pre-commit-config.yaml
- CHANGELOG.md
- baybe/objectives/desirability.py
- baybe/objectives/single.py
- baybe/parameters/base.py
- baybe/searchspace/continuous.py
- baybe/searchspace/core.py
- baybe/searchspace/discrete.py
- baybe/targets/base.py
- baybe/targets/binary.py
- baybe/targets/numerical.py
- pyproject.toml
- tests/test_deprecations.py
Fixes the `Target.transform` interface (compare also #289 and #398):
* Makes the input argument positional-only
* Changes the assumed types from `pd.DataFrame` to `pd.Series`
> Refactor target transform interface

- baybe/campaign.py
Was removed in PR #332 (commit 6371d976a07ffc0b44de9af87a71b6d5dc8d0bbe) but then mistakenly brought back in PR #319 (commit ac1fa4df16d4d278dcc12462fb61d24a4aa80376)
> Drop `batch_quantity` keyword

- .lockfiles/py310-dev.lock
- CHANGELOG.md
- pyproject.toml
Fixes #419 
Was also pushed as hotfix in the form of release `0.11.3` (c92975f9b602b163d8b9a3ed954d5bea3a74e99f)
> Unpin protobuf

- examples/Constraints_Discrete/dependency_constraints.py
Fixes two assert statements which did not take into account the smoke test value change: https://emdgroup.github.io/baybe/stable/examples/Constraints_Discrete/dependency_constraints.html
> Fix Asserts in Dependency Constraint Example

- baybe/utils/botorch_wrapper.py
This PR enables the use of `DTypeFloatTorch` in the BoTorch Wrapper.
Previously, this wrapper converted anything into `float64` precision. This can cause troubles an imprecision during the corresponding `forward` call in that function.
Note that this is one of the fixes required for GPU support, but since it is an issue on its own, I decided to already create this mini PR.
> Use correct precision in botorch wrapper

- CHANGELOG.md
- baybe/parameters/custom.py
- baybe/parameters/substance.py
- baybe/utils/dataframe.py
- tests/test_custom_parameter.py
- tests/test_substance_parameter.py
- tests/utils/test_dataframe.py
- tests/validation/test_parameter_validation.py
- Adds a utility `df_add_noise_to_degenerate_rows` to add noise to
degenerate rows of a numerical dataframe
- Adds a test for the utility
- Disallows `CustomDiscreteParameter` accepting `data` that has
degenerate rows
- Adds input tests for `CustomDiscreteParameter`
- Adds the fix to the `comp_df` of `SubstanceParameter`
- End-to-end test for degenerate substance encoding
> Fix rare degenerate `comp_df` bug

- CHANGELOG.md
- baybe/searchspace/discrete.py
- docs/userguide/envvars.md
Fixes #425 by requiring truthy/falsy values for `BAYBE_DEACTIVATE_POLARS` instead of accepting *any* value.
> Require truthy/falsy values for `BAYBE_DEACTIVATE_POLARS`

- CHANGELOG.md
- baybe/searchspace/continuous.py
- docs/userguide/envvars.md
This PR fixes the DType used when calculating the computational representation in a continuous space.
Currently, the dtype is not using any of our flags but infers it from the provided data, always yielding a `float64` representation. This causes troubles down the line, specifically for continuous constraints: These then turn out to have bounds in `float64` while other parts are in `float32`, making them unusable.
> Fix dtype in continuous comp rep

- .github/workflows/ci.yml
Run the CI tests regardless of the outcome of the `audit` job. Sometimes, we simply want to ignore the audit results in a certain PR but still make sure our tests pass.
> Drop CI audit dependence

- CHANGELOG.md
- README.md
- baybe/acquisition/base.py
- baybe/campaign.py
- baybe/constraints/base.py
- baybe/kernels/base.py
- baybe/objectives/base.py
- baybe/objectives/desirability.py
- baybe/priors/base.py
- baybe/recommenders/pure/base.py
- baybe/searchspace/_annotated.py
- baybe/searchspace/continuous.py
- baybe/searchspace/discrete.py
- baybe/serialization/core.py
- baybe/simulation/core.py
- baybe/simulation/scenarios.py
- baybe/simulation/transfer_learning.py
- baybe/surrogates/gaussian_process/kernel_factory.py
- baybe/utils/basic.py
- baybe/utils/dataframe.py
- docs/userguide/campaigns.md
- docs/userguide/constraints.md
- docs/userguide/recommenders.md
- docs/userguide/searchspace.md
- docs/userguide/serialization.md
- examples/Serialization/Serialization_Header.md
- tests/test_campaign.py
- tests/test_deprecations.py
Fixes #371 by making `SubspaceDiscrete` stateless.
* The `SubspaceDiscrete.metadata` attribute gets deprecated and the responsibility of metadata handling is shifted to `Campaign`
* The new mechanism is not yet final (see out of scope below) but designed in a way that allows to implement upcoming changes in a non-breaking manner. In particular:
* The metadata handling mechanism is redesigned in that the actual metadata representation is completely hidden from the user, i.e. campaign manages the data in form of private attributes. This is to avoid further lock-in into `pandas` as our search space backend and prepares for future search space improvements by abstracting away the specific implementation details, enabling us to easily offer other backends (polars, databases, etc) in the …
> Immutable searchspace

- .github/workflows/manual_benchmark.yml
- .lockfiles/py310-dev.lock
- CHANGELOG.md
- CONTRIBUTORS.md
- benchmarks/README.md
- benchmarks/__main__.py
- benchmarks/definition/config.py
- benchmarks/persistence/__init__.py
- benchmarks/persistence/persistence.py
- benchmarks/result/metadata.py
- benchmarks/result/result.py
- benchmarks/serialization.py
- mypy.ini
- pyproject.toml
Hi everyone,
This pull request introduces a class and a workflow designed to store the results of a benchmark run on an S3 bucket.
The key used for storage includes the identifier for the benchmark itself, the branch used, the release version, the current date and the commit hash in that order. Furthermore, boto3 package is added to interact with AWS components.
I look forward to your feedback.
> Add manual benchmark workflow and S3 result persistence

- CHANGELOG.md
- baybe/targets/numerical.py
- tests/hypothesis_strategies/targets.py
- tests/validation/test_target_validation.py
This PR fixes #449 by now checking whether a `NumericalTarget` has bounds if a transformation is provided.
Introduces a new step in the validation, raising a value error if the user provides a transformation but no bounds. Also adds an according test.
> Raise error when specifying transformation without bounds

- CHANGELOG.md
- baybe/searchspace/continuous.py
- tests/constraints/test_cardinality_constraint_continuous.py
When dropping parameters due to the use of cardinality constraints, it can happen that an attempt is made to create a Constraint without any parameters, causing the code to crash.
This PR introduces an explicit test for this scenario as well as a fix by only including constraints that still have parameters after dropping them.
This was observed when working on #345 and is necessary for continuing working on that.
> Fix empty constraints after dropping parameters

- baybe/utils/chemistry.py
Fix for #446 by introducing a robust check for different potential formats for feature names.
> Include robust check for extracting column names for fingerprints

- CHANGELOG.md
- examples/Basics/recommenders.py
> Correct typo in docs on acquisition functions

- CHANGELOG.md
- baybe/acquisition/base.py
- tests/integration/test_minimization.py
This PR fixes a critical bug introduced in #340 that has been present since version `0.10.1` and adds a corresponding test. The bug occurs when using improvement-based Monte Carlo acquisition functions (such as the default `qLogExpectedImprovement`) in with a single numerical target in `MIN` mode. The cause was a missing inversion of the `best_f` reference value.
> Fix minimization of improvement-based MC acquisition functions

- CHANGELOG.md
- baybe/searchspace/discrete.py
- docs/userguide/envvars.md
- tests/constraints/test_constraints_polars.py
Fixes the failing polars tests.
By default, `polars` gives no guarantees on the resulting row order of a join (see [here](https://github.com/pola-rs/polars/issues/20725)), meaning that our tests used to pass just by luck. This has changed since `polars==0.19.0`, which apparently included changes that affect the row order of our test dataframes. The PR fixes these tests by ignoring the row order during the equality check.
~~The current version of the polars cross join computing the Cartesian product currently makes no guarantees on the resulting row order (see [here](https://github.com/pola-rs/polars/issues/20725)). While strictly not a bug, this makes the behavior inconsistent with the corresponding pandas implementation and makes comparison more difficult. Accordingly, our tests started …
> Maintain row order after cross join

- CHANGELOG.md
- baybe/campaign.py
Reset the default of `allow_recommending_already_recommended` back to `False`, which was forgotten in #423.
> Reset flag default value

- CHANGELOG.md
- baybe/surrogates/gaussian_process/core.py
- baybe/surrogates/naive.py
- scipy fit is used for all cases now
- instead, the MLL type is switched based on whether TL is active or not
> Improve GP Fit

- .lockfiles/py310-dev.lock
- CHANGELOG.md
- baybe/constraints/continuous.py
- baybe/parameters/enum.py
- baybe/parameters/substance.py
- baybe/utils/chemistry.py
- docs/conf.py
- examples/Transfer_Learning/backtesting.py
- pyproject.toml
- tests/conftest.py
- tests/test_substance_parameter.py
`scikit-fingerprints` has updated to `1.13.0`. This broke our tests. This is caused by some of the new feature names having duplicates.
- bumped skfp version requirement to `>=0.13.1`
- excluded yanked matplotlib version
- Opened an [issue](https://github.com/scikit-fingerprints/scikit-fingerprints/issues/389) with scikit-fingerprints which triggered a fixed release
- Added support for the new `BCUT2D` fingerprint
- Also: the docs fail due to botorch links, which seems to have moved host location. Those were also fixed.
> Fix Substance Encodings

- benchmarks/result/result.py
Hi all,
this PR adds an unstructure hook to the result class to include the `init=False` attribute in the JSON. The current setting ignores these values so that the environment and version information is collected but won't become part of the stored file.
> Serialize python env and version data

- tests/test_kernels.py
There is a GPyTorch bug which causes test failure in some test for `LinearKernel`, see https://github.com/cornellius-gp/gpytorch/issues/2633 . Since it could take a while until new versions are out, this PR aims to fix the CI failing due to this.
Awaiting new gpytorch and botorch versions. The entire test is marked as xfail which will automatically inform us once it is corrected.
> XFail bugged test case

- tests/insights/test_shap.py
This is an attempt to fix the unrealiably failing SHAP plot tests.
The solution is motivated by this warning:
So it seems despite the `show` method being mocked, some plot objects are created and sort of persist. I suspect that there is some form of interaction effect here that causes [this line](https://github.com/shap/shap/blob/f1808f5c660cee80a1c67470362d876f1ed31028/shap/plots/_bar.py#L352) in thee shap module to return an emtpy tick label list, causing the `IndexError`. I have no idea though why it happens undeterministically. I  also was not able to pull this error out of the pytest into a separate script - there it always worked. Anyway, the issue is fixed by using `plt.close()` as suggested by the warning.
> Fix SHAP Plot Tests

- .github/workflows/manual_benchmark.yml
Hi everyone, as one of the requested changes from #493, this PR sets the GitHub-side runtime limit for the container to 24 hours. This refers to the GITHUB_TOKEN generated per job, which expires after that time period. I've also tested longer runtimes and found that we should also be safe to go up to 35 days if necessary. Further changes regarding parallelization may follow once discussed.
> Increase timeout for benchmark test to 1440 minutes (24 hours)

- benchmarks/definition/base.py
This PR adds two lines for logging which benchmark is started and how long it took with regards to #493.
I think the name and random seed is sufficient, but feel free to suggest the more or less information. 
An exemplary log looks like this:
> Add logging to indicate currently running benchmark and its runtime

- CHANGELOG.md
- baybe/exceptions.py
- baybe/utils/dataframe.py
- tests/utils/test_dataframe.py
- use vectorized operations instead of the for loop
- fixed column validations
- I tested that the result of the new version is always exactly equal to the old version
- added some basic pytests for the utility
- related to #344 
Here a resulting test looking at the speedup:
- speedup for the most realistic cases (`left_df` large versus `right_df`) approaches 4x from above
- for less relevant cases (`left_df` and `right_df` comparable in size or overall very small) the speedup can even be 40x
> Vectorize `fuzzy_row_match`

- baybe/surrogates/composite.py
Makes the serialization machinery of `_SurrogateGetter` compatible with Python 3.12
For details, see https://github.com/python-attrs/cattrs/issues/632
> Fix serialization errors on 3.12

- .github/workflows/manual_benchmark.yml
- CHANGELOG.md
- benchmarks/README.md
- benchmarks/__main__.py
- benchmarks/domains/__init__.py
Hi everyone, this PR adds benchmark parallelization as requested in #493 by using a matrix in the workflow. The container still needs to be deployed separately, so two matrixes are added. To start only a subset, the `__main__.py` was altered to take a CMD line argument so that existing domains don't have to be changed. The selection of different benchmarks was a bit tricky, so the separation of groups may be removed if it overcomplicates stuff.
I also noticed that the average CPU utilization was at about 48% for the 15 H benchmarks which ran recently:
So I changed CPUs requested compute from 16 vCPUs to 8.
> Pipeline benchmark parallelization

- tests/insights/test_shap.py
- catches exceptions due to current shap bugs and xfails the corresponding tests
- since not all of the issues are deterministic I went for exceptions catching rather than failing the test purely based on parameterization
- once there are no more xfails happening, we are sort of reminded that the issue might have been fixed on SHAP side
> Xfail bugged SHAP plot tests

- CHANGELOG.md
- baybe/acquisition/_builder.py
- baybe/acquisition/acqfs.py
- baybe/acquisition/base.py
- tests/hypothesis_strategies/acquisition.py
- tests/test_imports.py
This PR refactors the translation of BayBE acquisition functions into BoTorch acquisition functions, adopting concepts from the builder software pattern.
Rationale / Goals / Problems Addressed:
* No more monolithic spaghetti logic --> instead small isolated methods per attribute/concept
* No more partially overlapping if-conditions (which were the source of many bugs in the past)
* No more "string-based" logic
* Clear overview of existing arguments and (validation of) their types via the `BotorchAcquisitionArgs` class
* No more need to think about where/when to compute potentially costly intermediate quantities that are only needed in some cases --> (cached) properties instead
> Acquisition function builder

- CHANGELOG.md
- baybe/campaign.py
- baybe/constraints/discrete.py
- baybe/surrogates/base.py
- baybe/surrogates/composite.py
- docs/userguide/campaigns.md
- tests/conftest.py
- tests/docs/test_docs.py
- tests/test_campaign.py
- Adds a convenience function `posterior_stats` to the `Campaign`, returning a data frame of statistics about the target predictions
- Adds a test for this
- Mentions it in the user guide
- Changed the default acqf in conftest (which was still the non-log version)
Currently, for desirability objectives it is hardcoded that the statistics are for a single target called "Desirability", consistent with what `transform` does. Once posterior transforms are available, this logic needs to be adapted and it is expected that there is a flag in `DesirabilityObjective` that decides between scalarization or posterior_transforms. The latter case can then be treated exactly like all other targets.
> Add `Campaign.posterior_stats`

- CHANGELOG.md
- pyproject.toml
Fix installation if setuptools-scm version inference fails.
In the specific case, baybe was installed format the git repository inside a docker container that did not provide the ` git` command, leading setuptools-scm to fail. Same happens if for any reason the .git directory is missing (e.g. when downloading a tarbal from github).
The fallback version is set to `0.0+unknown` to ensure we adhere to PyPa (https://packaging.python.org/en/latest/specifications/version-specifiers/#examples-of-compliant-version-schemes) while still ensuring any user will be able to recognize this as a non-standard version identifier.
Fixes #521
> Provide version fallback in case scm fails to infer version during installation

- tox.ini
Makes our tox lockfile command compatible with `uv>=0.6.0` which introduced a breaking change regarding the semantics of the python version specifier.
> Fix lockfile creation for uv>=0.6.0

- CHANGELOG.md
- baybe/acquisition/__init__.py
- baybe/acquisition/acqfs.py
- baybe/acquisition/base.py
Since multi-ouput is now supported we might as well add support for this alternative to qLogNEHVI
Notes:
- changed `AcquisitionFunction.supports_multi_output` to an explicitly set class var
- for this acqf, botorch uses an already heavily abbreviated term, so I made `abbreviation` identical to the original name
- the name stands for batch logarithmic noisy pareto efficient global optimization
- Botorch-latest already has an option `incremental` enabling to chagne qLogNParEGO's behavior in a way that sounds very similar to what `sequential` does. But since its not released I left that out
Here the result with the existing Pareto example indicating this basically works (the actual code change for this was not pushed):
Its also clear that this seems to be inferior to qLogNEHVI, I think this …
> Add qLogNParEGO

- baybe/campaign.py
- baybe/exceptions.py
- baybe/insights/shap.py
- tests/insights/test_shap.py
A minor improvement that throws an understandable error in case `posterior_stats` is called with empty candidates on a campaign with no measurements (useful for the API)
> Posterior Stats: Catch No Measurements Case

- CHANGELOG.md
- baybe/_optional/chem.py
- baybe/_optional/info.py
- baybe/_optional/insights.py
- baybe/_optional/ngboost.py
- baybe/_optional/onnx.py
- baybe/_optional/polars.py
- baybe/_optional/simulation.py
- baybe/_optional/sklearn_extra.py
- baybe/exceptions.py
- baybe/recommenders/pure/nonpredictive/clustering.py
- pyproject.toml
- tests/test_integration.py
- tests/test_iterations.py
- tests/test_pending_experiments.py
Turns `scikit-learn-extra` into an optional dependency via our optional import system (see #525).
> Make `scikit-learn-extra` optional

- .lockfiles/py310-dev.lock
- CHANGELOG.md
- README.md
- baybe/__init__.py
- pyproject.toml
Partially addresses #525 by dropping `setuptools-scm` as a runtime dependency.
> Make `setuptools-scm` optional

- tests/insights/test_shap.py
Since `shap==0.47.1` was published, @fabianliebig's fix is published and the `xfail` for that error is not necessary anymore and should be removed again from the test
Afaik the other error is also fixed but no release available
> Remove xfail for fixed SHAP case

- CHANGELOG.md
- README.md
- baybe/acquisition/_builder.py
- baybe/acquisition/acqfs.py
- baybe/campaign.py
- baybe/exceptions.py
- baybe/surrogates/base.py
- baybe/surrogates/composite.py
- baybe/utils/dataframe.py
- baybe/utils/validation.py
- docs/userguide/async.md
- docs/userguide/objectives.md
- docs/userguide/surrogates.md
- tests/conftest.py
- tests/test_campaign.py
- tests/test_input_output.py
- tests/test_partial_measurements.py
- tests/utils/test_dataframe.py
Enables partial measurements when composite surrogates and `ParetoObjective` are used.
- Added method `Campaign.update_measurements` enabling the update of
already existing measurements (should come in handy in pending
measurement scenarios)
- Target validation now allows NaNs
- Minimal adjustments in pure and composite surrogates now either block
NaNs (failing at recommendation attempt) or drop the corresponding rows when creating
single-target surrogates (this is what enables partial measurements)
- Added documentation mostly focused on the async workflows page
> Enable Partial Measurements

- .lockfiles/py310-dev.lock
- .pre-commit-config.yaml
- baybe/constraints/continuous.py
- baybe/insights/shap.py
- baybe/parameters/utils.py
- baybe/recommenders/meta/sequential.py
- baybe/simulation/_imputation.py
- baybe/utils/clustering_algorithms/third_party/kmedoids.py
- docs/userguide/utils.md
- examples/Constraints_Continuous/hybrid_space.py
- examples/Constraints_Continuous/linear_constraints.py
- examples/Constraints_Discrete/custom_constraints.py
- examples/Constraints_Discrete/dependency_constraints.py
- examples/Constraints_Discrete/exclusion_constraints.py
- examples/Constraints_Discrete/prodsum_constraints.py
- examples/Multi_Target/desirability.py
- examples/Searchspaces/continuous_space.py
- examples/Searchspaces/discrete_space.py
- examples/Searchspaces/hybrid_space.py
- pyproject.toml
- tests/conftest.py
- tests/constraints/test_cardinality_constraint_continuous.py
- tests/hypothesis_strategies/utils.py
- tests/test_campaign.py
- tests/test_input_output.py
- tests/test_meta_recommenders.py
- tests/test_substance_parameter.py
- tests/utils/test_augmentation.py
- tests/utils/test_sampling_algorithms.py
Brings our dev tools up-to-date
> Bump dev tools versions

- CHANGELOG.md
- baybe/recommenders/pure/nonpredictive/sampling.py
- baybe/utils/sampling_algorithms.py
- tests/utils/test_sampling_algorithms.py
> Tie breaking for FPS

- CHANGELOG.md
- baybe/simulation/scenarios.py
I noticed that `simulate_scenarios` doesn't actually saturate all cores on my machine. The `run_combos` function takes a `parallel` parameter that we can set to true to spread the simulation across all cores.
https://xyzpy.readthedocs.io/en/latest/gen_parallel.html
> Enable parallel execution of scenarios

- CHANGELOG.md
- baybe/acquisition/_builder.py
- streamlit/surrogate_models.py
Fixes a wrong type check that resulted in `PosteriorStandardDeviation` always being minimized (regardless of its own `maximize` flag) when used in combination with a single `MIN` target, because the flag was overwritten in the code lines below. The other two active learning acquisition functions were not affected since the code execution does not reach the corresponding line in these cases.
> Fix guard clause

- baybe/_optional/onnx.py
- mypy.ini
- tests/conftest.py
This PR introduces a robust import of the function `split_complex_to_pairs` of ONNX.
The reason is that this function seems to have been deprecated in `onnx>=1.18.0`, but some other packages still rely on it. To avoid an explicit version pin, this robust import is introduced.
Note that this also requires a slightly whacky import in `conftest`, since the actual import of the optional dependency only happens later, causing an error when pytest wants to access the fixture.
> Make import of deprecated ONNX function robust

- .github/workflows/ci.yml
- .github/workflows/regular.yml
- .github/workflows/release.yml
- CHANGELOG.md
- CONTRIBUTING.md
- baybe/_optional/onnx.py
- mypy.ini
- pyproject.toml
- tests/README.md
- tests/conftest.py
- tests/docs/test_examples.py
- tests/serialization/test_surrogate_serialization.py
- tests/test_custom_surrogate.py
- tox.ini
Enables Python 3.13 and reverts the ONNX monkeypatch from #555 since a fix is now on the way from the `skl2onnx` side.
> Enable Python 3.13

- CHANGELOG.md
- baybe/surrogates/utils.py
A small typing improvement to enable static type checking and autocompletion of surrogates decorated with `catch_constant_targets`
> Add missing decorator return type

- .lockfiles/py310-dev.lock
- examples/Custom_Surrogates/custom_pretrained.py
- pyproject.toml
- tests/conftest.py
- tests/serialization/test_surrogate_serialization.py
- tests/test_custom_surrogate.py
recently we had to introduce workarounds due to [an issue with onnx and sklearn-onnx](https://github.com/onnx/sklearn-onnx/pull/1181)
[Since these are fixed now](https://github.com/onnx/sklearn-onnx/releases/tag/v1.19.1) I'm
- removing the workarounds
- bumping the version requirement for the package
> Remove ONNX Workarounds

- CHANGELOG.md
- baybe/recommenders/pure/nonpredictive/clustering.py
- baybe/recommenders/pure/nonpredictive/sampling.py
- baybe/serialization/core.py
- baybe/surrogates/custom.py
- baybe/surrogates/linear.py
- baybe/surrogates/ngboost.py
- baybe/surrogates/random_forest.py
- baybe/surrogates/validation.py
- baybe/utils/sampling_algorithms.py
- examples/Custom_Surrogates/surrogate_params.py
- tests/test_custom_surrogate.py
- tests/test_imports.py
- tests/test_surrogate.py
- Lazy-load `scikit-learn` and `scipy`
- This required changes to how the optional `model_params` are validated for `RandomForestSurrogate`, `NGBoostSurrogate` and `BayesianLinearSurrogate`. These are now checked against a hardcoded `TypedDict`
- A few things were required to make it work. E.g. cattrs does not complain if `123.3` is provided for a field that has `iunt`-only type hint as it cuts the float and considers this valid. Hence I used a converter thats more strict via custom structure hooks. This is not entirely perfect, as eg the basic baybe constructor is not that strict, hence its possible to bypass this strictness of an object is created from a json_string
- I've moved the onnx model instantiation to the point where its needed. This means the onnx string is not validated …
> Lazy-load sklearn and scipy + adjust required model validations

- CHANGELOG.md
- baybe/campaign.py
- baybe/exceptions.py
- baybe/parameters/base.py
- baybe/parameters/categorical.py
- baybe/parameters/utils.py
- baybe/recommenders/pure/base.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/searchspace/discrete.py
- baybe/utils/dataframe.py
- tests/hypothesis_strategies/parameters.py
- tests/test_searchspace.py
- tests/utils/test_dataframe.py
This is response to Issue #542 
- `CategoricalParameter` (and the derived `TaskParameter`) now also support Boolean entries in `values`. This also has consequneces for the type hint of `active_values`
- `SubspaceDiscrete.from_dataframe` now handles the special case of a column containing only Booleans by assigning a `CategoricalParameter(encoding="INT")` to it, effectively fixing the problem reported in the issue
- `fuzzy_row_match` now also contains a conditional cast to float before attempting distance calculation, otherwise one could still break it by reading in data eg from a columns containing mixed bool/float values
Notes:
- The treatment of Booleans in pandas can be tricky, e.g. a `series.dtype` will say bool, but each individual element is `np.bool`. Those two dtypes are not …
> Allow Booleans for `CategoricalParameter`

- CHANGELOG.md
- pyproject.toml
Fixes a wrong Python version specifier in `pyproject.toml` from `<=3.13` to `<3.14`.
> Fix Python version specifier

- README.md
Our pipeline badges currently work without filters, which pretty much makes them useless, because all pipeline runs will update their status (even when triggered from development or PR branches, which will fail most of the time). This PR makes them point to the main branch only. Ideally, the view should be further filtered down to e.g. exclude cancelled runs, but I don't think this is possible.
> Link badges to main branch

- CHANGELOG.md
- baybe/objectives/desirability.py
- baybe/targets/numerical.py
- baybe/transformations/__init__.py
- baybe/transformations/base.py
- baybe/transformations/basic.py
- baybe/transformations/composite.py
- baybe/transformations/utils.py
- baybe/utils/basic.py
- tests/hypothesis_strategies/transformations.py
- tests/serialization/test_objective_serialization.py
- tests/serialization/test_target_serialization.py
- tests/serialization/test_transformation_serialization.py
- tests/test_deprecations.py
- tests/test_objective.py
- tests/test_targets.py
- tests/test_transformations.py
- tests/validation/test_objective_validation.py
* Splits the existing transformation `core.py` module into `basic.py` and `composite.py` (similar to other subpackages like `kernels`)
* Changes transformation chaining operator from `+` to `|`
* Adds `AdditiveTransformation` and `MultiplicativeTransformation` classes
* Introduces `get_codomain` in addition to `get_image`
> Composite transformations

- benchmarks/result/result.py
Replaces `importlib_metadata` with `importlib.metadata` in the benchmark package. The latter is supposed to be used for versions above Python 3.8 and avoids a `mypy` issue that showed up in #205.
> Use `importlib.metadata`

- CHANGELOG.md
- baybe/constraints/conditions.py
- baybe/constraints/continuous.py
- docs/userguide/constraints.md
- examples/Constraints_Continuous/hybrid_space.py
- examples/Constraints_Continuous/linear_constraints.py
- examples/Mixtures/traditional.py
- tests/hypothesis_strategies/constraints.py
Fixes #579 
Due to missing converters, exotic type usage could break the serialization (see issue).
> Harmonize `float` Related Converters and Validators in Constraints and Conditions

- CHANGELOG.md
- baybe/campaign.py
- baybe/recommenders/meta/base.py
- baybe/recommenders/pure/base.py
- baybe/recommenders/pure/bayesian/base.py
- baybe/utils/validation.py
- tests/validation/test_campaign_validation.py
Fixes #571 
This PR contains further work to avoid the problem described in the issue. This now works for both stateful and stateless mode. The corresponding validations use the new utility `validate_object_names`
**Notes**:
I've also added the validation to meta-recommenders. This has the consequence that an error will also be thrown if the meta recommender uses a non-predictive recommender which does not use an objective. Overlapping names would not strictly represent a problem for this specific situation, however I would argue this still represents a misconfiguration that should be avoided.
> Forbid Overlap in Target and Parameter Names

- CHANGELOG.md
- baybe/acquisition/_builder.py
- baybe/objectives/base.py
- baybe/objectives/desirability.py
- baybe/objectives/pareto.py
- baybe/objectives/single.py
- baybe/simulation/_imputation.py
- baybe/targets/numerical.py
- baybe/transformations/base.py
- baybe/transformations/basic.py
- baybe/transformations/composite.py
- tests/serialization/test_objective_serialization.py
- tests/test_deprecations.py
- tests/test_lookup.py
- tests/test_objective.py
- tests/test_targets.py
In the previous code, the role of `NumericalTarget` was twofold:
* Specification of the quantity to be optimized (i.e. defining a named signal and which derivative of that signal is to be optimized, declared via a `transformation`) + defining the corresponding optimization direction (i.e. via the `minimize` flag)
* Implementing the translation into the actual quantity entering the optimization engine, i.e. applying the actual effect of the `minimize` flag via optional negation of the target.
This was nice from a user story because it allowed for the simple `targets are always transformed and then maximized` narrative. However, applying also the second step from above actually mixed the two concerns of `what is to be optimized` (i.e. the target specification) and `how it is optimized`. …
> Move target negation to objective

- CHANGELOG.md
- baybe/campaign.py
- tests/test_campaign.py
- tests/test_pending_experiments.py
Fixes #654. 
Improvements that are out of scope for this bugfix PR:
* Less strict cache invalidation: For several cases, the PR clears the cache too conservatively (see also comments added).  In particular, caching is not used at all / immediately cleared as soon as pending experiments enter the stage. By storing the previous recommendation context and using more fine-grained conditions, cache usage could be further extended.
* Instead of manually maintaining the caching logic and conditions, we might also consider switching to a built-in approach (e.g. using `@cached` directly on the recommender level), which would potentially simply the logic significantly and avoid future bugs due to not having to think about edge cases. However, the caching approach would then be even stricter as it …
> Make `allow_*` flags work with caching

- baybe/parameters/substance.py
- baybe/transformations/composite.py
- baybe/utils/metadata.py
- benchmarks/definition/regression.py
- pyproject.toml
- uv.lock
Now fixed upstream in the new `attrs` version.
* https://github.com/python-attrs/attrs/pull/1448
* https://github.com/python-attrs/attrs/pull/1449
> Drop attrs typing workaround
